// Nordiske gryteretter - Høyprotein versjon (ca. 40g protein per porsjon)
const recipes = [
    // KJØTT
    {
        id: 1,
        name: "Lapskaus",
        type: "kjøtt",
        emoji: "🥩",
        description: "Klassisk norsk gryte med saftig storfekjøtt og rotgrønnsaker",
        time: "2 timer",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~520 kcal per porsjon",
        ingredients: [
            "800g storfekjøtt i terninger (magert)",
            "5 store poteter",
            "4 gulrøtter",
            "1 kålrot",
            "3 løk",
            "1.5 liter kjøttbuljong",
            "3 ss smør",
            "2 laurbærblad",
            "1 ts sort pepper (hel)",
            "Salt og pepper",
            "Rikelig med persille til pynt"
        ],
        instructions: [
            "Brun kjøttet i smør i en stor gryte",
            "Ta ut kjøttet og fres løken til den er gyllen",
            "Legg kjøttet tilbake og ha i buljong og krydder",
            "La koke under lokk i 1 time",
            "Skrell og kutt rotgrønnsaker og poteter i store biter",
            "Legg grønnsakene i gryten og kok videre i 40-50 min",
            "Smak til med salt og pepper",
            "Topp med rikelig persille"
        ],
        serveTips: "Server med grovt brød og rømme. For ekstra protein: Server med cottage cheese eller gresk yoghurt ved siden."
    },
    {
        id: 2,
        name: "Kalops",
        type: "kjøtt",
        emoji: "🥩",
        description: "Svensk klassiker med mørt oksekjøtt og dyp, rik saus",
        time: "2.5 timer",
        servings: "4 porsjoner",
        protein: "~42g per porsjon",
        calories: "~580 kcal per porsjon",
        ingredients: [
            "900g oksekjøtt (magert)",
            "4 store løk",
            "5 laurbærblad",
            "15 allehåndekorn",
            "3 ss mel",
            "1 liter oksekraft",
            "2 ss tomatpuré",
            "1 dl rødvin (valgfritt)",
            "3 ss smør",
            "Salt og pepper"
        ],
        instructions: [
            "Skjær kjøttet i store terninger",
            "Brun kjøttet godt i smør, gjør dette i omganger",
            "Skjær løken i skiver og fres med kjøttet",
            "Ha i tomatpuré, stek 1 min",
            "Dryss over mel og rør godt",
            "Hell i kraft (og evt. rødvin), legg i krydder",
            "La småkoke under lokk i 2 timer, rør av og til",
            "Smak til med salt og pepper"
        ],
        serveTips: "Server med kokte poteter, tyttebær og sylteagurk. Perfekt med kokt egg ved siden for ekstra protein."
    },
    {
        id: 3,
        name: "Reinsdyrgryte",
        type: "kjøtt",
        emoji: "🦌",
        description: "Samisk spesialitet med reinsdyr, sopp og kremet, vill saus",
        time: "1.5 timer",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~620 kcal per porsjon",
        ingredients: [
            "750g reinsdyrkjøtt",
            "3 sjalottløk",
            "400g blandede sopp (kantareller om tilgjengelig)",
            "4 dl kremfløte",
            "3 dl viltfond",
            "3 ss smør",
            "2 ss tyttebærsyltetøy",
            "2 fedd hvitløk",
            "Frisk timian og rosmarin",
            "Salt og pepper"
        ],
        instructions: [
            "Skjær kjøttet i tynne strimler",
            "Brun kjøttet raskt i smør, ta ut",
            "Fres løk og sopp",
            "Ha i fond og fløte, kok opp",
            "Legg kjøttet tilbake, smak til med tyttebær",
            "La småkoke i 30 min",
            "Smak til med krydder",
            "Server med potetstappe og tyttebær"
        ]
    },

    // KYLLING
    {
        id: 4,
        name: "Hønsegryte med rotgrønnsaker",
        type: "kylling",
        emoji: "🐔",
        description: "Kremet kyllinggryte med søte rotgrønnsaker og friske urter",
        time: "1 time",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~550 kcal per porsjon",
        ingredients: [
            "750g kyllingfilet",
            "4 gulrøtter",
            "1 kålrot",
            "3 pastinakker",
            "2 løk",
            "1 purre",
            "7 dl kyllingbuljong",
            "3 dl kremfløte",
            "3 ss smør",
            "Frisk timian og persille",
            "2 fedd hvitløk",
            "Salt, pepper, muskatnøtt"
        ],
        instructions: [
            "Skjær kyllingen i biter og brun i smør",
            "Ta ut kyllingen, fres løk",
            "Skrell og kutt rotgrønnsaker i biter",
            "Hell i buljong og legg i grønnsaker",
            "La koke i 20 min",
            "Legg kyllingen tilbake, ha i fløte",
            "Kok i 10 min til",
            "Smak til med timian, salt og pepper"
        ]
    },
    {
        id: 5,
        name: "Kyllinggryte med eple og purre",
        type: "kylling",
        emoji: "🍎",
        description: "Nordisk smak med syrlige epler og mild purre - Høyprotein",
        time: "45 min",
        servings: "4 porsjoner",
        protein: "~38g per porsjon",
        calories: "~580 kcal per porsjon",
        ingredients: [
            "800g kyllinglår (utbenet)",
            "3 epler (syrlige, f.eks. Granny Smith)",
            "3 purrer",
            "2 sjalottløk",
            "5 dl kyllingbuljong",
            "3 dl matfløte",
            "3 ss smør",
            "2 ss sennep",
            "2 ss honning",
            "Frisk timian og persille",
            "1 fedd hvitløk",
            "Salt, pepper"
        ],
        instructions: [
            "Brun kyllinglårene godt i smør",
            "Ta ut og fres purre og sjalottløk i skiver",
            "Skjær epler i båter, legg i og karamelliser lett",
            "Hell i buljong og fløte",
            "Legg kyllingen tilbake med timian",
            "La småkoke i 30 min",
            "Rør inn sennep og honning",
            "Smak til med salt og pepper",
            "Topp med frisk persille"
        ],
        serveTips: "Server med kokt ris eller ovnsbakte poteter. For ekstra protein: Topp med ristede mandler eller cashewnøtter."
    },

    // FISK
    {
        id: 6,
        name: "Fiskesuppe (Bergensk)",
        type: "fisk",
        emoji: "🐟",
        description: "Klassisk vestlandsk fiskesuppe med torsk og reker - Høyprotein",
        time: "40 min",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~420 kcal per porsjon",
        ingredients: [
            "700g torskefilet",
            "300g reker (skalte)",
            "4 gulrøtter",
            "2 purrer",
            "5 poteter",
            "2 sjalottløk",
            "1 liter fiskebuljong",
            "3 dl kremfløte",
            "3 ss smør",
            "1 dl hvitvin (valgfritt)",
            "2 laurbærblad",
            "Fersk dill, persille, salt, hvit pepper"
        ],
        instructions: [
            "Fres sjalottløk i smør til gyllen",
            "Skrell og kutt grønnsaker i pene terninger",
            "Kok grønnsaker møre i buljong med laurbærblad i 15 min",
            "Skjær fisken i store biter",
            "Legg fisken forsiktig i gryten",
            "La trekke i 5-7 min (ikke kok, fisken skal være mør)",
            "Rør inn fløte og reker, varm forsiktig",
            "Smak til med salt og hvit pepper",
            "Topp med rikelig fersk dill og persille"
        ],
        serveTips: "Server med hjemmebakt brød og smør. For ekstra protein: Legg ved hardkokte egg i halver eller server med cottage cheese på siden."
    },
    {
        id: 7,
        name: "Laksegryte med dill",
        type: "fisk",
        emoji: "🐟",
        description: "Kremet laksegryte med spinat, dill og sitrus",
        time: "30 min",
        servings: "4 porsjoner",
        protein: "~42g per porsjon",
        calories: "~560 kcal per porsjon",
        ingredients: [
            "750g laksfilet",
            "3 sjalottløk",
            "4 dl fiskebuljong",
            "3 dl kremfløte",
            "300g fersk spinat",
            "1 stor bunt fersk dill",
            "Saft og skall av 1 sitron",
            "2 ss hvitvin (valgfritt)",
            "2 ss smør",
            "Salt, hvit pepper"
        ],
        instructions: [
            "Fres sjalottløk i smør",
            "Hell i buljong og fløte",
            "Kok opp og la småkoke 5 min",
            "Skjær laksen i biter",
            "Legg laksen og spinat i gryten",
            "La trekke i 5 min",
            "Rør inn hakket dill og sitronsaft",
            "Server med pasta eller ris"
        ]
    },
    {
        id: 8,
        name: "Skrei med bacon og løk",
        type: "fisk",
        emoji: "🥓",
        description: "Vinterens hvite gull med røkt bacon - Høyprotein",
        time: "35 min",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~520 kcal per porsjon",
        ingredients: [
            "800g skreifilet",
            "200g bacon (god kvalitet)",
            "3 store løk",
            "1 purre",
            "6 poteter",
            "5 dl fiskebuljong",
            "3 dl rømme",
            "2 ss smør",
            "1 fedd hvitløk",
            "Fersk persille og dill",
            "Salt, sort pepper"
        ],
        instructions: [
            "Stek bacon sprø i gryten, ta ut",
            "Fres løk og purre i baconfettet til myk",
            "Kutt poteter i skiver, legg i",
            "Hell i buljong, kok møre i 15 min",
            "Skjær skrei i store biter",
            "Legg fisken forsiktig oppi, la trekke 5-7 min",
            "Rør inn rømme og bacon",
            "Smak til med salt og pepper",
            "Topp med rikelig persille og dill"
        ],
        serveTips: "Server med godt brød og smør. For ekstra protein: Topp med ekstra rømme eller gresk yoghurt og hardkokt egg."
    },

    // VEGETAR
    {
        id: 9,
        name: "Rotgrønnsaksgryte med kikerter",
        type: "vegetar",
        emoji: "🥕",
        description: "Fargerik og mettende gryte med nordiske rotgrønnsaker - Høyprotein",
        time: "50 min",
        servings: "4 porsjoner",
        protein: "~38g per porsjon",
        calories: "~480 kcal per porsjon",
        ingredients: [
            "4 gulrøtter",
            "1 kålrot",
            "3 pastinakker",
            "1 sellerrot",
            "3 løk",
            "3 fedd hvitløk",
            "400g hermetiske tomater",
            "800g hermetiske kikerter (2 bokser)",
            "250g røde linser",
            "8 dl grønnsaksbuljong",
            "2 dl kokosmjølk",
            "3 ss tomatpuré",
            "Frisk timian og rosmarin",
            "1 ts spisskummen",
            "Salt, pepper",
            "3 ss olivenolje"
        ],
        instructions: [
            "Skrell og kutt alle rotgrønnsaker i jevne biter",
            "Fres løk og hvitløk i olje til gyllen",
            "Legg i rotgrønnsaker, la frese 7-8 min",
            "Ha i tomatpuré, stek 1 min",
            "Hell i tomater, buljong og kokosmjølk",
            "Krydre med timian, rosmarin og spisskummen",
            "Legg i kikerter og linser",
            "La småkoke i 30-40 min til grønnsakene er møre",
            "Smak til med salt og pepper"
        ],
        serveTips: "Server med fullkornsbrød og hummus. For ekstra protein: Topp med ristede solsikkefrø, gresk yoghurt eller fetaost."
    },
    {
        id: 10,
        name: "Kålgryte med belgfrukter",
        type: "vegetar",
        emoji: "🥬",
        description: "Sunn og mettende gryte med kål og linser - Høyprotein",
        time: "45 min",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~450 kcal per porsjon",
        ingredients: [
            "½ stort hodekål",
            "4 gulrøtter",
            "3 løk",
            "1 paprika",
            "300g røde linser",
            "400g hermetiske svarte bønner",
            "400g hermetiske kikerter",
            "400g hermetiske tomater",
            "1 liter grønnsaksbuljong",
            "2 dl kokosmjølk",
            "4 fedd hvitløk",
            "3 cm fersk ingefær",
            "2 ts spisskummen",
            "1 ts paprika",
            "1 ts karri",
            "Salt, pepper",
            "3 ss olivenolje",
            "Fersk koriander eller persille"
        ],
        instructions: [
            "Fres løk, hvitløk og ingefær i olje",
            "Kutt kål, gulrøtter og paprika i strimler",
            "Legg grønnsaker i gryten, fres 7 min",
            "Ha i krydder, stek 1 min til duftende",
            "Hell i linser, bønner, tomater og buljong",
            "La småkoke i 25 min",
            "Rør inn kokosmjølk, kok 5 min til",
            "Smak til med salt og pepper",
            "Topp med fersk koriander eller persille"
        ],
        serveTips: "Server med fullkornsbrød eller quinoa. For ekstra protein: Topp med gresk yoghurt, cottage cheese eller ristede nøtter."
    },
    {
        id: 11,
        name: "Soppsgryte med perlebygg og tempeh",
        type: "vegetar",
        emoji: "🍄",
        description: "Rik og smakfull sopp-gryte med nordisk korn - Høyprotein",
        time: "1 time",
        servings: "4 porsjoner",
        protein: "~38g per porsjon",
        calories: "~520 kcal per porsjon",
        ingredients: [
            "600g blandede sopp (sjampinjong, østerssopp, kantareller)",
            "400g tempeh (i terninger)",
            "2.5 dl perlebygg",
            "250g edamambønner",
            "3 sjalottløk",
            "4 fedd hvitløk",
            "8 dl grønnsaksbuljong",
            "3 dl matfløte eller havregrøt",
            "1 dl hvitvin (valgfritt)",
            "3 ss smør eller olivenolje",
            "3 ss soyasaus",
            "Frisk timian, rosmarin og persille",
            "1 ss dijon sennep",
            "Salt, pepper"
        ],
        instructions: [
            "Kok perlebygg i saltet vann i 30 min, hell av",
            "Rens og skjær soppen i biter",
            "Fres sjalottløk og hvitløk i smør",
            "Stek tempeh til gyllen, ta ut",
            "Stek soppen i omganger til gyllen og væsken er fordampet",
            "Hell i vin (eller buljong), la koke inn",
            "Ha i buljong, fløte, soyasaus og sennep",
            "Legg i perlebygg, tempeh og edamambønner",
            "La småkoke i 15 min",
            "Smak til med timian, salt og pepper",
            "Topp med frisk persille"
        ],
        serveTips: "Server med surdeigsbrød og en grønn salat. For ekstra protein: Topp med ristede valnøtter eller solsikkefrø, eller server med cottage cheese."
    },
    {
        id: 12,
        name: "Ertesuppe (Vegetar)",
        type: "vegetar",
        emoji: "🟢",
        description: "Nordisk klassiker i vegetarversjon - Høyprotein",
        time: "1.5 timer",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~490 kcal per porsjon",
        ingredients: [
            "500g gule erter (tørket)",
            "200g grønne linser",
            "4 gulrøtter",
            "1 stor kålrot",
            "3 løk",
            "1 purre",
            "3 fedd hvitløk",
            "2 liter grønnsaksbuljong",
            "1 dl havredrikk eller matfløte",
            "Fersk timian og laurbærblad",
            "1 ts allehånde",
            "Salt, pepper",
            "Sennep til servering",
            "Fersk persille"
        ],
        instructions: [
            "Bløtlegg ertene over natten, skyll godt",
            "Kok ertene i buljong med laurbærblad i 1 time",
            "Skrell og kutt grønnsaker i terninger",
            "Fres løk, purre og hvitløk i bunnen av en annen gryte",
            "Legg grønnsaker i ertegryten sammen med linser",
            "Kok videre i 30-40 min til alt er mørt",
            "Krydre med timian, allehånde, salt og pepper",
            "Rør inn havredrikk eller fløte",
            "Server med sennep, fersk persille og knekkebrød"
        ],
        serveTips: "Server med godt brød og ost. For ekstra protein: Topp med hardkokt egg, cottage cheese eller revet ost."
    }
];
