// Nordiske gryteretter - Høyprotein versjon (ca. 40g protein per porsjon)
const recipes = [
    // KJØTT
    {
        id: 1,
        name: "Lapskaus",
        type: "kjøtt",
        cuisine: "nordisk",
        emoji: "🥩",
        description: "Klassisk norsk gryte med saftig storfekjøtt og rotgrønnsaker",
        time: "2 timer",
        cookTime: "lang",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~520 kcal per porsjon",
        ingredients: [
            "800g storfekjøtt i terninger (magert)",
            "5 store poteter",
            "4 gulrøtter",
            "1 kålrot",
            "3 løk",
            "1.5 liter kjøttbuljong",
            "3 ss smør",
            "2 laurbærblad",
            "1 ts sort pepper (hel)",
            "Salt og pepper",
            "Rikelig med persille til pynt"
        ],
        instructions: [
            "Brun kjøttet i smør i en stor gryte",
            "Ta ut kjøttet og fres løken til den er gyllen",
            "Legg kjøttet tilbake og ha i buljong og krydder",
            "La koke under lokk i 1 time",
            "Skrell og kutt rotgrønnsaker og poteter i store biter",
            "Legg grønnsakene i gryten og kok videre i 40-50 min",
            "Smak til med salt og pepper",
            "Topp med rikelig persille"
        ],
        serveTips: "Server med grovt brød og rømme. For ekstra protein: Server med cottage cheese eller gresk yoghurt ved siden."
    },
    {
        id: 2,
        name: "Kalops",
        type: "kjøtt",
        cuisine: "nordisk",
        emoji: "🥩",
        description: "Svensk klassiker med mørt oksekjøtt og dyp, rik saus",
        time: "2.5 timer",
        cookTime: "lang",
        servings: "4 porsjoner",
        protein: "~42g per porsjon",
        calories: "~580 kcal per porsjon",
        ingredients: [
            "900g oksekjøtt (magert)",
            "4 store løk",
            "5 laurbærblad",
            "15 allehåndekorn",
            "3 ss mel",
            "1 liter oksekraft",
            "2 ss tomatpuré",
            "1 dl rødvin (valgfritt)",
            "3 ss smør",
            "Salt og pepper"
        ],
        instructions: [
            "Skjær kjøttet i store terninger",
            "Brun kjøttet godt i smør, gjør dette i omganger",
            "Skjær løken i skiver og fres med kjøttet",
            "Ha i tomatpuré, stek 1 min",
            "Dryss over mel og rør godt",
            "Hell i kraft (og evt. rødvin), legg i krydder",
            "La småkoke under lokk i 2 timer, rør av og til",
            "Smak til med salt og pepper"
        ],
        serveTips: "Server med kokte poteter, tyttebær og sylteagurk. Perfekt med kokt egg ved siden for ekstra protein."
    },
    {
        id: 3,
        name: "Reinsdyrgryte",
        type: "kjøtt",
        cuisine: "nordisk",
        emoji: "🦌",
        description: "Samisk spesialitet med reinsdyr, sopp og kremet, vill saus",
        time: "1.5 timer",
        cookTime: "lang",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~620 kcal per porsjon",
        ingredients: [
            "750g reinsdyrkjøtt",
            "3 sjalottløk",
            "400g blandede sopp (kantareller om tilgjengelig)",
            "4 dl kremfløte",
            "3 dl viltfond",
            "3 ss smør",
            "2 ss tyttebærsyltetøy",
            "2 fedd hvitløk",
            "Frisk timian og rosmarin",
            "Salt og pepper"
        ],
        instructions: [
            "Skjær kjøttet i tynne strimler",
            "Brun kjøttet raskt i smør, ta ut",
            "Fres løk og sopp",
            "Ha i fond og fløte, kok opp",
            "Legg kjøttet tilbake, smak til med tyttebær",
            "La småkoke i 30 min",
            "Smak til med krydder",
            "Server med potetstappe og tyttebær"
        ]
    },

    // KYLLING
    {
        id: 4,
        name: "Hønsegryte med rotgrønnsaker",
        type: "kylling",
        cuisine: "nordisk",
        emoji: "🐔",
        description: "Kremet kyllinggryte med søte rotgrønnsaker og friske urter",
        time: "1 time",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~550 kcal per porsjon",
        ingredients: [
            "750g kyllingfilet",
            "4 gulrøtter",
            "1 kålrot",
            "3 pastinakker",
            "2 løk",
            "1 purre",
            "7 dl kyllingbuljong",
            "3 dl kremfløte",
            "3 ss smør",
            "Frisk timian og persille",
            "2 fedd hvitløk",
            "Salt, pepper, muskatnøtt"
        ],
        instructions: [
            "Skjær kyllingen i biter og brun i smør",
            "Ta ut kyllingen, fres løk",
            "Skrell og kutt rotgrønnsaker i biter",
            "Hell i buljong og legg i grønnsaker",
            "La koke i 20 min",
            "Legg kyllingen tilbake, ha i fløte",
            "Kok i 10 min til",
            "Smak til med timian, salt og pepper"
        ]
    },
    {
        id: 5,
        name: "Kyllinggryte med eple og purre",
        type: "kylling",
        cuisine: "nordisk",
        emoji: "🍎",
        description: "Nordisk smak med syrlige epler og mild purre - Høyprotein",
        time: "45 min",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~38g per porsjon",
        calories: "~580 kcal per porsjon",
        ingredients: [
            "800g kyllinglår (utbenet)",
            "3 epler (syrlige, f.eks. Granny Smith)",
            "3 purrer",
            "2 sjalottløk",
            "5 dl kyllingbuljong",
            "3 dl matfløte",
            "3 ss smør",
            "2 ss sennep",
            "2 ss honning",
            "Frisk timian og persille",
            "1 fedd hvitløk",
            "Salt, pepper"
        ],
        instructions: [
            "Brun kyllinglårene godt i smør",
            "Ta ut og fres purre og sjalottløk i skiver",
            "Skjær epler i båter, legg i og karamelliser lett",
            "Hell i buljong og fløte",
            "Legg kyllingen tilbake med timian",
            "La småkoke i 30 min",
            "Rør inn sennep og honning",
            "Smak til med salt og pepper",
            "Topp med frisk persille"
        ],
        serveTips: "Server med kokt ris eller ovnsbakte poteter. For ekstra protein: Topp med ristede mandler eller cashewnøtter."
    },

    // FISK
    {
        id: 6,
        name: "Fiskesuppe (Bergensk)",
        type: "fisk",
        cuisine: "nordisk",
        emoji: "🐟",
        description: "Klassisk vestlandsk fiskesuppe med torsk og reker - Høyprotein",
        time: "40 min",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~420 kcal per porsjon",
        ingredients: [
            "700g torskefilet",
            "300g reker (skalte)",
            "4 gulrøtter",
            "2 purrer",
            "5 poteter",
            "2 sjalottløk",
            "1 liter fiskebuljong",
            "3 dl kremfløte",
            "3 ss smør",
            "1 dl hvitvin (valgfritt)",
            "2 laurbærblad",
            "Fersk dill, persille, salt, hvit pepper"
        ],
        instructions: [
            "Fres sjalottløk i smør til gyllen",
            "Skrell og kutt grønnsaker i pene terninger",
            "Kok grønnsaker møre i buljong med laurbærblad i 15 min",
            "Skjær fisken i store biter",
            "Legg fisken forsiktig i gryten",
            "La trekke i 5-7 min (ikke kok, fisken skal være mør)",
            "Rør inn fløte og reker, varm forsiktig",
            "Smak til med salt og hvit pepper",
            "Topp med rikelig fersk dill og persille"
        ],
        serveTips: "Server med hjemmebakt brød og smør. For ekstra protein: Legg ved hardkokte egg i halver eller server med cottage cheese på siden."
    },
    {
        id: 7,
        name: "Laksegryte med dill",
        type: "fisk",
        cuisine: "nordisk",
        emoji: "🐟",
        description: "Kremet laksegryte med spinat, dill og sitrus",
        time: "30 min",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~42g per porsjon",
        calories: "~560 kcal per porsjon",
        ingredients: [
            "750g laksfilet",
            "3 sjalottløk",
            "4 dl fiskebuljong",
            "3 dl kremfløte",
            "300g fersk spinat",
            "1 stor bunt fersk dill",
            "Saft og skall av 1 sitron",
            "2 ss hvitvin (valgfritt)",
            "2 ss smør",
            "Salt, hvit pepper"
        ],
        instructions: [
            "Fres sjalottløk i smør",
            "Hell i buljong og fløte",
            "Kok opp og la småkoke 5 min",
            "Skjær laksen i biter",
            "Legg laksen og spinat i gryten",
            "La trekke i 5 min",
            "Rør inn hakket dill og sitronsaft",
            "Server med pasta eller ris"
        ]
    },
    {
        id: 8,
        name: "Skrei med bacon og løk",
        type: "fisk",
        cuisine: "nordisk",
        emoji: "🥓",
        description: "Vinterens hvite gull med røkt bacon - Høyprotein",
        time: "35 min",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~520 kcal per porsjon",
        ingredients: [
            "800g skreifilet",
            "200g bacon (god kvalitet)",
            "3 store løk",
            "1 purre",
            "6 poteter",
            "5 dl fiskebuljong",
            "3 dl rømme",
            "2 ss smør",
            "1 fedd hvitløk",
            "Fersk persille og dill",
            "Salt, sort pepper"
        ],
        instructions: [
            "Stek bacon sprø i gryten, ta ut",
            "Fres løk og purre i baconfettet til myk",
            "Kutt poteter i skiver, legg i",
            "Hell i buljong, kok møre i 15 min",
            "Skjær skrei i store biter",
            "Legg fisken forsiktig oppi, la trekke 5-7 min",
            "Rør inn rømme og bacon",
            "Smak til med salt og pepper",
            "Topp med rikelig persille og dill"
        ],
        serveTips: "Server med godt brød og smør. For ekstra protein: Topp med ekstra rømme eller gresk yoghurt og hardkokt egg."
    },

    // VEGETAR
    {
        id: 9,
        name: "Rotgrønnsaksgryte med kikerter",
        type: "vegetar",
        cuisine: "nordisk",
        emoji: "🥕",
        description: "Fargerik og mettende gryte med nordiske rotgrønnsaker",
        time: "50 min",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~22g per porsjon",
        calories: "~380 kcal per porsjon",
        ingredients: [
            "4 gulrøtter",
            "1 kålrot",
            "3 pastinakker",
            "1 sellerrot",
            "3 løk",
            "3 fedd hvitløk",
            "400g hermetiske tomater",
            "400g hermetiske kikerter",
            "100g røde linser",
            "8 dl grønnsaksbuljong",
            "2 dl kokosmjølk",
            "3 ss tomatpuré",
            "Frisk timian og rosmarin",
            "1 ts spisskummen",
            "Salt, pepper",
            "3 ss olivenolje"
        ],
        instructions: [
            "Skrell og kutt alle rotgrønnsaker i jevne biter",
            "Fres løk og hvitløk i olje til gyllen",
            "Legg i rotgrønnsaker, la frese 7-8 min",
            "Ha i tomatpuré, stek 1 min",
            "Hell i tomater, buljong og kokosmjølk",
            "Krydre med timian, rosmarin og spisskummen",
            "Legg i kikerter og linser",
            "La småkoke i 30-40 min til grønnsakene er møre",
            "Smak til med salt og pepper"
        ],
        serveTips: "Server med fullkornsbrød og hummus. For ekstra protein: Topp med ristede solsikkefrø, gresk yoghurt eller fetaost."
    },
    {
        id: 10,
        name: "Kålgryte med belgfrukter",
        type: "vegetar",
        cuisine: "nordisk",
        emoji: "🥬",
        description: "Sunn og mettende gryte med kål og linser",
        time: "45 min",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~20g per porsjon",
        calories: "~350 kcal per porsjon",
        ingredients: [
            "½ stort hodekål",
            "4 gulrøtter",
            "3 løk",
            "1 paprika",
            "150g røde linser",
            "400g hermetiske kikerter",
            "400g hermetiske tomater",
            "1 liter grønnsaksbuljong",
            "2 dl kokosmjølk",
            "4 fedd hvitløk",
            "3 cm fersk ingefær",
            "2 ts spisskummen",
            "1 ts paprika",
            "1 ts karri",
            "Salt, pepper",
            "3 ss olivenolje",
            "Fersk koriander eller persille"
        ],
        instructions: [
            "Fres løk, hvitløk og ingefær i olje",
            "Kutt kål, gulrøtter og paprika i strimler",
            "Legg grønnsaker i gryten, fres 7 min",
            "Ha i krydder, stek 1 min til duftende",
            "Hell i linser, bønner, tomater og buljong",
            "La småkoke i 25 min",
            "Rør inn kokosmjølk, kok 5 min til",
            "Smak til med salt og pepper",
            "Topp med fersk koriander eller persille"
        ],
        serveTips: "Server med fullkornsbrød eller quinoa. For ekstra protein: Topp med gresk yoghurt, cottage cheese eller ristede nøtter."
    },
    {
        id: 11,
        name: "Soppsgryte med perlebygg",
        type: "vegetar",
        cuisine: "nordisk",
        emoji: "🍄",
        description: "Rik og smakfull sopp-gryte med nordisk korn",
        time: "1 time",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~18g per porsjon",
        calories: "~420 kcal per porsjon",
        ingredients: [
            "600g blandede sopp (sjampinjong, østerssopp, kantareller)",
            "2 dl perlebygg",
            "3 sjalottløk",
            "4 fedd hvitløk",
            "8 dl grønnsaksbuljong",
            "3 dl matfløte eller havregrøt",
            "1 dl hvitvin (valgfritt)",
            "3 ss smør eller olivenolje",
            "2 ss soyasaus",
            "Frisk timian, rosmarin og persille",
            "1 ss dijon sennep",
            "Salt, pepper"
        ],
        instructions: [
            "Kok perlebygg i saltet vann i 30 min, hell av",
            "Rens og skjær soppen i biter",
            "Fres sjalottløk og hvitløk i smør",
            "Stek tempeh til gyllen, ta ut",
            "Stek soppen i omganger til gyllen og væsken er fordampet",
            "Hell i vin (eller buljong), la koke inn",
            "Ha i buljong, fløte, soyasaus og sennep",
            "Legg i perlebygg, tempeh og edamambønner",
            "La småkoke i 15 min",
            "Smak til med timian, salt og pepper",
            "Topp med frisk persille"
        ],
        serveTips: "Server med surdeigsbrød og en grønn salat. For ekstra protein: Topp med ristede valnøtter eller solsikkefrø, eller server med cottage cheese."
    },
    {
        id: 12,
        name: "Ertesuppe (Vegetar)",
        type: "vegetar",
        cuisine: "nordisk",
        emoji: "🟢",
        description: "Nordisk klassiker i vegetarversjon",
        time: "1.5 timer",
        cookTime: "lang",
        servings: "4 porsjoner",
        protein: "~24g per porsjon",
        calories: "~420 kcal per porsjon",
        ingredients: [
            "400g gule erter (tørket)",
            "4 gulrøtter",
            "1 stor kålrot",
            "3 løk",
            "1 purre",
            "3 fedd hvitløk",
            "2 liter grønnsaksbuljong",
            "1 dl havredrikk eller matfløte",
            "Fersk timian og laurbærblad",
            "1 ts allehånde",
            "Salt, pepper",
            "Sennep til servering",
            "Fersk persille"
        ],
        instructions: [
            "Bløtlegg ertene over natten, skyll godt",
            "Kok ertene i buljong med laurbærblad i 1 time",
            "Skrell og kutt grønnsaker i terninger",
            "Fres løk, purre og hvitløk i bunnen av en annen gryte",
            "Legg grønnsaker i ertegryten sammen med linser",
            "Kok videre i 30-40 min til alt er mørt",
            "Krydre med timian, allehånde, salt og pepper",
            "Rør inn havredrikk eller fløte",
            "Server med sennep, fersk persille og knekkebrød"
        ],
        serveTips: "Server med godt brød og ost. For ekstra protein: Topp med hardkokt egg, cottage cheese eller revet ost."
    },

    // MEKSIKANSK
    {
        id: 13,
        name: "Chili con Carne",
        type: "kjøtt",
        cuisine: "meksikansk",
        emoji: "🌶️",
        description: "Klassisk meksikansk gryte med kjøttdeig, bønner og chilismak",
        time: "1 time",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~520 kcal per porsjon",
        ingredients: [
            "700g kjøttdeig (magert)",
            "400g svarte bønner (hermetiske)",
            "400g kidneybønner (hermetiske)",
            "400g hermetiske tomater",
            "2 paprika (rød og gul)",
            "3 løk",
            "4 fedd hvitløk",
            "3 ss tomatpuré",
            "6 dl kjøttbuljong",
            "2 ts spisskummen",
            "2 ts chilipulver",
            "1 ts paprika",
            "1 ts oregano",
            "Salt, pepper",
            "2 ss olivenolje",
            "Fersk koriander"
        ],
        instructions: [
            "Fres løk og hvitløk i olje til myke",
            "Skjær paprika i terninger, legg i",
            "Brun kjøttdeig, del opp godt",
            "Ha i tomatpuré, stek 1 min",
            "Krydre med spisskummen, chili, paprika og oregano",
            "Hell i tomater og buljong",
            "Legg i bønner, la småkoke i 30 min",
            "Smak til med salt og pepper",
            "Topp med fersk koriander"
        ],
        serveTips: "Server med ris, nachos og rømme. For ekstra protein: Topp med revet ost og gresk yoghurt."
    },

    // FRANSK
    {
        id: 14,
        name: "Coq au Vin",
        type: "kylling",
        cuisine: "fransk",
        emoji: "🍷",
        description: "Klassisk fransk kyllinggryte med rødvin, bacon og sopp",
        time: "2 timer",
        cookTime: "lang",
        servings: "4 porsjoner",
        protein: "~42g per porsjon",
        calories: "~580 kcal per porsjon",
        ingredients: [
            "1kg kyllinglår (med bein)",
            "200g bacon",
            "300g sjampinjong",
            "20 sjalottløk (små)",
            "4 fedd hvitløk",
            "5 dl rødvin (god kvalitet)",
            "3 dl kyllingbuljong",
            "3 ss tomatpuré",
            "3 ss smør",
            "2 ss mel",
            "3 laurbærblad",
            "Frisk timian",
            "Salt, pepper"
        ],
        instructions: [
            "Brun kyllinglårene i smør, ta ut",
            "Stek bacon sprø, ta ut",
            "Fres sjalottløk og sopp til gylne",
            "Dryss over mel, rør godt",
            "Hell i rødvin og buljong, kok opp",
            "Legg kyllingen tilbake med bacon",
            "Tilsett laurbærblad og timian",
            "La småkoke under lokk i 1.5 timer",
            "Smak til med salt og pepper"
        ],
        serveTips: "Server med kokte poteter eller pasta. For ekstra protein: Server med hardkokt egg eller ekstra kylling."
    },

    // ITALIENSK
    {
        id: 15,
        name: "Osso Buco",
        type: "kjøtt",
        cuisine: "italiensk",
        emoji: "🇮🇹",
        description: "Italiensk kalvegryte med sitrus, hvitvin og gremolata",
        time: "2.5 timer",
        cookTime: "lang",
        servings: "4 porsjoner",
        protein: "~45g per porsjon",
        calories: "~620 kcal per porsjon",
        ingredients: [
            "1.2kg kalveskank (i skiver)",
            "3 løk",
            "3 gulrøtter",
            "3 stilker selleri",
            "4 fedd hvitløk",
            "400g hermetiske tomater",
            "3 dl hvitvin",
            "4 dl kyllingbuljong",
            "3 ss tomatpuré",
            "Skall og saft av 1 sitron",
            "Frisk basilikum og persille",
            "2 laurbærblad",
            "3 ss olivenolje",
            "Salt, pepper"
        ],
        instructions: [
            "Brun kalveskankene i olje, ta ut",
            "Fres finhakket løk, gulrot og selleri",
            "Ha i tomatpuré, stek 1 min",
            "Hell i vin, la koke inn halvparten",
            "Tilsett tomater og buljong",
            "Legg kjøttet tilbake med laurbær",
            "La småkoke under lokk i 2 timer",
            "Tilsett sitronsaft og skall",
            "Topp med fersk basilikum og persille"
        ],
        serveTips: "Server med risotto eller polenta. For ekstra protein: Server med parmesan og grønne bønner."
    },

    // ASIATISK
    {
        id: 16,
        name: "Thai Red Curry",
        type: "kylling",
        cuisine: "asiatisk",
        emoji: "🍛",
        description: "Kremet thai-gryte med rød currypaste, kokosmjølk og limeblade",
        time: "35 min",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~38g per porsjon",
        calories: "~560 kcal per porsjon",
        ingredients: [
            "750g kyllingbryst",
            "400ml kokosmjølk (full-fat)",
            "3 ss rød currypaste",
            "2 paprika (forskjellige farger)",
            "200g sukkererter",
            "1 aubergine",
            "3 sjalottløk",
            "3 cm fersk ingefær",
            "3 fedd hvitløk",
            "2 dl kyllingbuljong",
            "2 ss fiskesaus",
            "1 ss sukker",
            "4 limeblade (eller saft av 1 lime)",
            "Fersk basilikum og koriander",
            "2 ss olje"
        ],
        instructions: [
            "Stek currypaste i olje i 1 min til duftende",
            "Hell i kokosmjølk, rør godt",
            "Skjær kylling i biter, legg i",
            "Kutt grønnsaker i biter, tilsett",
            "Hell i buljong, kok opp",
            "La småkoke i 15 min",
            "Smak til med fiskesaus og sukker",
            "Tilsett limeblade",
            "Topp med fersk basilikum og koriander"
        ],
        serveTips: "Server med jasminris eller nudler. For ekstra protein: Tilsett tofu eller edamambønner."
    },

    // Flere meksikanske
    {
        id: 17,
        name: "Pescado a la Veracruzana",
        type: "fisk",
        cuisine: "meksikansk",
        emoji: "🐟",
        description: "Meksikansk fiskegryte med tomater, oliver og kapers",
        time: "40 min",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~450 kcal per porsjon",
        ingredients: [
            "800g hvit fisk (torsk eller sei)",
            "400g hermetiske tomater",
            "2 paprika",
            "3 løk",
            "4 fedd hvitløk",
            "100g grønne oliver",
            "3 ss kapers",
            "2 jalapeño (fersk eller hermetisk)",
            "3 dl fiskebuljong",
            "2 ss olivenolje",
            "1 ts spisskummen",
            "Fersk koriander og lime",
            "Salt, pepper"
        ],
        instructions: [
            "Fres løk og hvitløk i olje",
            "Skjær paprika i strimler, legg i",
            "Ha i tomater, oliver, kapers og jalapeño",
            "Krydre med spisskummen",
            "Hell i buljong, la småkoke 10 min",
            "Skjær fisken i biter, legg forsiktig i",
            "La trekke i 5-7 min",
            "Topp med koriander og limesaft"
        ],
        serveTips: "Server med ris og avokado. For ekstra protein: Server med svarte bønner ved siden."
    },
    {
        id: 18,
        name: "Frijoles Charros (Cowboy-bønner)",
        type: "vegetar",
        cuisine: "meksikansk",
        emoji: "🫘",
        description: "Meksikansk vegetargryte med pinto-bønner og chipotle",
        time: "50 min",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~22g per porsjon",
        calories: "~380 kcal per porsjon",
        ingredients: [
            "800g pinto-bønner (hermetiske)",
            "400g hermetiske tomater",
            "3 paprika (ulike farger)",
            "4 løk",
            "5 fedd hvitløk",
            "2 chipotle chili (i adobo)",
            "8 dl grønnsaksbuljong",
            "2 ts spisskummen",
            "1 ts oregano",
            "Fersk koriander og lime",
            "3 ss olivenolje",
            "Salt, pepper"
        ],
        instructions: [
            "Fres løk og hvitløk i olje",
            "Skjær paprika i terninger, legg i",
            "Hakk chipotle, tilsett",
            "Ha i tomater og buljong",
            "Krydre med spisskummen og oregano",
            "Legg i bønner, la småkoke 30 min",
            "Smak til med salt og pepper",
            "Topp med koriander og lime"
        ],
        serveTips: "Server med tortillas og guacamole. For ekstra protein: Topp med cottage cheese eller gresk yoghurt."
    },

    // Flere franske
    {
        id: 19,
        name: "Bouillabaisse",
        type: "fisk",
        cuisine: "fransk",
        emoji: "🦞",
        description: "Provençalsk fiskegryte med saffran og aioli",
        time: "1 time",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~42g per porsjon",
        calories: "~520 kcal per porsjon",
        ingredients: [
            "600g blandet fisk (torsk, sei, laks)",
            "300g reker",
            "200g blåskjell",
            "400g hermetiske tomater",
            "3 sjalottløk",
            "4 fedd hvitløk",
            "1 liter fiskebuljong",
            "2 dl hvitvin",
            "0.5g saffran",
            "Skall av 1 appelsin",
            "3 laurbærblad",
            "Frisk persille og fennikel",
            "3 ss olivenolje",
            "Salt, pepper"
        ],
        instructions: [
            "Fres sjalottløk og hvitløk i olje",
            "Ha i tomater, saffran og appelsinskall",
            "Hell i vin og buljong, kok opp",
            "Legg i laurbær, la småkoke 20 min",
            "Skjær fisk i biter, legg forsiktig i",
            "Tilsett reker og blåskjell",
            "La koke 5 min til skjellene åpner seg",
            "Topp med persille"
        ],
        serveTips: "Server med hvitløksbrød og rouille. For ekstra protein: Tilsett flere reker eller fisk."
    },
    {
        id: 20,
        name: "Ratatouille",
        type: "vegetar",
        cuisine: "fransk",
        emoji: "🍆",
        description: "Provençalsk grønnsaksgryte med timian og basilikum",
        time: "1 time",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~18g per porsjon",
        calories: "~320 kcal per porsjon",
        ingredients: [
            "2 auberginer",
            "3 squash",
            "4 tomater",
            "3 paprika",
            "4 løk",
            "6 fedd hvitløk",
            "400g hermetiske tomater",
            "400g cannellini-bønner (hermetiske)",
            "5 dl grønnsaksbuljong",
            "Frisk basilikum og timian",
            "4 ss olivenolje",
            "Salt, pepper"
        ],
        instructions: [
            "Skjær alle grønnsaker i terninger",
            "Fres løk og hvitløk i olje",
            "Legg i aubergine, paprika og squash",
            "Fres 10 min",
            "Ha i tomater, bønner, linser og buljong",
            "Krydre med timian",
            "La småkoke 30 min",
            "Topp med fersk basilikum"
        ],
        serveTips: "Server med baguette. For ekstra protein: Topp med fetaost eller gresk yoghurt."
    },

    // Flere italienske
    {
        id: 22,
        name: "Ribollita",
        type: "vegetar",
        cuisine: "italiensk",
        emoji: "🥬",
        description: "Toskansk brød- og grønnkålsuppe med cannellini-bønner",
        time: "1 time",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~22g per porsjon",
        calories: "~410 kcal per porsjon",
        ingredients: [
            "400g grønnkål",
            "600g cannellini-bønner (hermetiske)",
            "400g hermetiske tomater",
            "3 gulrøtter",
            "3 stilker selleri",
            "4 løk",
            "6 fedd hvitløk",
            "1 liter grønnsaksbuljong",
            "200g gammelt brød (i biter)",
            "Frisk rosmarin og salvie",
            "80g parmesan",
            "5 ss olivenolje",
            "Salt, pepper"
        ],
        instructions: [
            "Fres løk, selleri og gulrot i olje",
            "Ha i hvitløk, rosmarin og salvie",
            "Tilsett tomater og buljong",
            "Legg i bønner, kok 20 min",
            "Finhakk grønnkål, legg i",
            "Kok 10 min til",
            "Rør inn brødbiter",
            "La stå 10 min, topp med parmesan"
        ],
        serveTips: "Server med ekstra olivenolje og parmesan. For ekstra protein: Tilsett flere bønner eller cottage cheese."
    },

    // Flere asiatiske
    {
        id: 23,
        name: "Tom Yum (Thai fiskesuppe)",
        type: "fisk",
        cuisine: "asiatisk",
        emoji: "🦐",
        description: "Sur og sterk thai-suppe med reker og sitrongress",
        time: "35 min",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~38g per porsjon",
        calories: "~380 kcal per porsjon",
        ingredients: [
            "600g hvit fisk eller reker",
            "200g sjampinjong",
            "3 tomater",
            "3 stilker sitrongress",
            "5 cm galangal (eller ingefær)",
            "4 limeblade",
            "3 thai-chili",
            "8 dl fiskebuljong",
            "3 ss fiskesaus",
            "3 ss limesaft",
            "2 ts sukker",
            "Fersk koriander",
            "2 ss olje"
        ],
        instructions: [
            "Knekk sitrongress, skjær galangal i skiver",
            "Kok buljong med sitrongress, galangal og limeblade i 10 min",
            "Fjern aromaer eller la være",
            "Skjær sopp og tomater, legg i",
            "Kok 5 min",
            "Skjær fisk i biter, legg i med chili",
            "Kok 3-4 min",
            "Smak til med fiskesaus, lime og sukker",
            "Topp med koriander"
        ],
        serveTips: "Server med jasminris. For ekstra protein: Tilsett flere reker eller tofu."
    },
    {
        id: 24,
        name: "Mapo Tofu",
        type: "vegetar",
        cuisine: "asiatisk",
        emoji: "🌶️",
        description: "Sichuan tofu-gryte med fermenterte bønner og sichuan-pepper",
        time: "30 min",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~24g per porsjon",
        calories: "~390 kcal per porsjon",
        ingredients: [
            "600g fast tofu",
            "3 vårløk",
            "5 fedd hvitløk",
            "3 cm fersk ingefær",
            "2 ss doubanjiang (fermentert bønnepaste)",
            "1 ss sichuan-pepper",
            "3 dl grønnsaksbuljong",
            "2 ss soyasaus",
            "1 ss sesamolje",
            "2 ts maisstivelse",
            "2 ss olje",
            "Fersk koriander"
        ],
        instructions: [
            "Skjær tofu i terninger",
            "Fres hvitløk, ingefær og vårløk",
            "Ha i doubanjiang, stek 1 min",
            "Tilsett sichuan-pepper",
            "Hell i buljong og soyasaus",
            "Legg i tofu og edamambønner forsiktig",
            "La småkoke 10 min",
            "Rør inn maisstivelse blandet med vann",
            "Drypp sesamolje over, topp med koriander"
        ],
        serveTips: "Server med ris. For ekstra protein: Tilsett mer tofu eller edamambønner."
    },

    // SPANSK CUISINE
    {
        id: 25,
        name: "Rabo de Toro (Oksehale-gryte)",
        type: "kjøtt",
        cuisine: "spansk",
        emoji: "🐂",
        description: "Andalusisk klassiker med oksehale, rødvin og paprika",
        time: "3.5 timer",
        cookTime: "lang",
        servings: "4 porsjoner",
        protein: "~42g per porsjon",
        calories: "~620 kcal per porsjon",
        ingredients: [
            "1.2kg oksehale (i skiver)",
            "3 løk",
            "4 gulrøtter",
            "6 fedd hvitløk",
            "5 dl rødvin",
            "4 dl oksekraft",
            "400g hermetiske tomater",
            "3 ss tomatpuré",
            "2 ts røkt paprika",
            "2 laurbærblad",
            "Frisk timian",
            "3 ss olivenolje",
            "Salt, pepper"
        ],
        instructions: [
            "Brun oksehalen godt i olje, ta ut",
            "Fres løk, gulrot og hvitløk",
            "Ha i tomatpuré og røkt paprika, stek 1 min",
            "Hell i rødvin, la koke inn halvparten",
            "Tilsett tomater og kraft",
            "Legg oksehalen tilbake med laurbær og timian",
            "La småkoke under lokk i 3 timer til kjøttet faller av benet",
            "Smak til med salt og pepper"
        ],
        serveTips: "Server med ovnsbakte poteter. For ekstra protein: Server med hardkokt egg."
    },
    {
        id: 26,
        name: "Pollo al Chilindron",
        type: "kylling",
        cuisine: "spansk",
        emoji: "🍗",
        description: "Aragonsk kyllinggryte med paprika, tomat og chorizo",
        time: "1 time",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~540 kcal per porsjon",
        ingredients: [
            "800g kyllinglår",
            "150g chorizo",
            "4 paprika (røde)",
            "3 løk",
            "5 fedd hvitløk",
            "400g hermetiske tomater",
            "2 dl kyllingbuljong",
            "1 dl hvitvin",
            "2 ts paprika",
            "Frisk persille",
            "3 ss olivenolje",
            "Salt, pepper"
        ],
        instructions: [
            "Brun kyllinglårene i olje, ta ut",
            "Skjær chorizo og paprika, fres med løk",
            "Ha i hvitløk, stek 1 min",
            "Tilsett tomater, vin og buljong",
            "Krydre med paprika",
            "Legg kyllingen tilbake",
            "La småkoke i 40 min",
            "Topp med persille"
        ],
        serveTips: "Server med crusty bread eller ris. For ekstra protein: Tilsett flere chorizo."
    },
    {
        id: 27,
        name: "Marmitako (Baskisk tunfiskgryte)",
        type: "fisk",
        cuisine: "spansk",
        emoji: "🐟",
        description: "Baskisk fiskegryte med tunfisk, poteter og paprika",
        time: "45 min",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~38g per porsjon",
        calories: "~480 kcal per porsjon",
        ingredients: [
            "700g fersk tunfisk (eller god hermetisk)",
            "6 poteter",
            "2 paprika (rød og grønn)",
            "3 løk",
            "4 fedd hvitløk",
            "400g hermetiske tomater",
            "5 dl fiskebuljong",
            "2 ts paprika",
            "1 ts cayennepepper",
            "Frisk persille",
            "4 ss olivenolje",
            "Salt, pepper"
        ],
        instructions: [
            "Fres løk og hvitløk i olje",
            "Skjær paprika og poteter i biter, legg i",
            "Ha i tomater og buljong",
            "Krydre med paprika og cayenne",
            "Kok potetene møre i 20 min",
            "Skjær tunfisk i biter, legg forsiktig i",
            "La trekke 5 min (ikke overkok)",
            "Topp med persille"
        ],
        serveTips: "Server med hvitløksbrød. For ekstra protein: Tilsett flere tunfisk eller hvite bønner."
    },
    {
        id: 28,
        name: "Pisto Manchego",
        type: "vegetar",
        cuisine: "spansk",
        emoji: "🫑",
        description: "Spansk ratatouille med paprika, squash og egg",
        time: "45 min",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~20g per porsjon",
        calories: "~360 kcal per porsjon",
        ingredients: [
            "3 paprika (ulike farger)",
            "2 squash",
            "2 auberginer",
            "4 tomater",
            "4 løk",
            "6 fedd hvitløk",
            "400g cannellini-bønner (hermetiske)",
            "1 dl olivenolje",
            "2 ts paprika",
            "Frisk basilikum",
            "Salt, pepper"
        ],
        instructions: [
            "Skjær alle grønnsaker i terninger",
            "Fres løk og hvitløk i olje",
            "Legg i paprika og aubergine, fres 10 min",
            "Ha i squash og tomater",
            "Krydre med paprika",
            "Tilsett bønner",
            "La småkoke i 20 min",
            "Topp med basilikum"
        ],
        serveTips: "Server med brød og manchego-ost. For ekstra protein: Topp med stekt egg eller fetaost."
    },

    // INDISK CUISINE
    {
        id: 29,
        name: "Rogan Josh",
        type: "kjøtt",
        cuisine: "indisk",
        emoji: "🍛",
        description: "Kashmiri lammegryte med yoghurt og varme krydder",
        time: "2 timer",
        cookTime: "lang",
        servings: "4 porsjoner",
        protein: "~44g per porsjon",
        calories: "~580 kcal per porsjon",
        ingredients: [
            "900g lammekjøtt (eller storfekjøtt)",
            "3 dl gresk yoghurt",
            "4 løk",
            "6 cm fersk ingefær",
            "8 fedd hvitløk",
            "400g hermetiske tomater",
            "4 dl kjøttbuljong",
            "3 ss garam masala",
            "2 ts kashmiri chili",
            "2 ts koriander",
            "1 ts kardemomme",
            "4 ss ghee eller olje",
            "Fersk koriander",
            "Salt"
        ],
        instructions: [
            "Skjær kjøttet i biter, bland med yoghurt og krydder, mariner 30 min",
            "Fres løk, ingefær og hvitløk i ghee",
            "Ha i marinert kjøtt, brun godt",
            "Tilsett tomater og buljong",
            "La småkoke under lokk i 1.5 timer",
            "Smak til med salt",
            "Topp med koriander"
        ],
        serveTips: "Server med basmati-ris og naan. For ekstra protein: Server med linser ved siden."
    },
    {
        id: 30,
        name: "Chicken Tikka Masala",
        type: "kylling",
        cuisine: "indisk",
        emoji: "🍗",
        description: "Kremet kyllinggryte med tomatsaus og varme krydder",
        time: "1 time",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~42g per porsjon",
        calories: "~560 kcal per porsjon",
        ingredients: [
            "800g kyllingbryst",
            "2 dl gresk yoghurt",
            "400g hermetiske tomater",
            "3 dl kremfløte",
            "4 løk",
            "6 cm fersk ingefær",
            "8 fedd hvitløk",
            "3 ss garam masala",
            "2 ts kurkuma",
            "2 ts paprika",
            "1 ts chilipulver",
            "4 ss ghee",
            "Fersk koriander",
            "Salt"
        ],
        instructions: [
            "Skjær kylling i biter, bland med yoghurt og halvparten av krydder, mariner 30 min",
            "Fres løk, ingefær og hvitløk til gyllen",
            "Ha i resten av krydder, stek 1 min",
            "Tilsett tomater, kok 10 min",
            "Stek kyllingen separat til gyllen",
            "Legg kyllingen i sausen",
            "Rør inn fløte, la småkoke 15 min",
            "Topp med koriander"
        ],
        serveTips: "Server med ris og naan. For ekstra protein: Server med kikerter eller linser."
    },
    {
        id: 31,
        name: "Goan Fish Curry",
        type: "fisk",
        cuisine: "indisk",
        emoji: "🐟",
        description: "Syrlig fiskecurry fra Goa med kokosmjølk og tamarind",
        time: "40 min",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~520 kcal per porsjon",
        ingredients: [
            "800g hvit fisk (torsk eller sei)",
            "400ml kokosmjølk",
            "3 tomater",
            "4 løk",
            "6 cm ingefær",
            "6 fedd hvitløk",
            "3 ss tamarindpasta",
            "2 ss korianderfrø",
            "2 ts kurkuma",
            "1 ts chilipulver",
            "1 ts sennepsfrø",
            "4 ss olje",
            "Fersk koriander",
            "Salt"
        ],
        instructions: [
            "Fres sennepsfrø i olje til de spretter",
            "Ha i løk, ingefær og hvitløk",
            "Tilsett krydder, stek 1 min",
            "Legg i tomater, kok 5 min",
            "Hell i kokosmjølk og tamarind",
            "Skjær fisk i biter, legg forsiktig i",
            "La småkoke 10 min",
            "Topp med koriander"
        ],
        serveTips: "Server med ris. For ekstra protein: Tilsett reker eller kikerter."
    },
    {
        id: 32,
        name: "Chana Masala",
        type: "vegetar",
        cuisine: "indisk",
        emoji: "🫘",
        description: "Krydret kikertgryte med tomat og garam masala",
        time: "45 min",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~22g per porsjon",
        calories: "~420 kcal per porsjon",
        ingredients: [
            "800g hermetiske kikerter",
            "400g hermetiske tomater",
            "4 løk",
            "6 cm ingefær",
            "6 fedd hvitløk",
            "3 ss garam masala",
            "2 ts kurkuma",
            "2 ts koriander",
            "1 ts spisskummen",
            "1 ts chilipulver",
            "4 ss olje",
            "Fersk koriander og lime",
            "Salt"
        ],
        instructions: [
            "Fres løk, ingefær og hvitløk til gyllen",
            "Ha i alle krydder, stek 1 min",
            "Tilsett tomater, kok 10 min",
            "Legg i kikerter med litt væske",
            "La småkoke 20 min",
            "Mos noen kikerter for tykkelse",
            "Smak til med salt",
            "Topp med koriander og lime"
        ],
        serveTips: "Server med ris og naan. For ekstra protein: Topp med cottage cheese eller paneer."
    },

    // JAPANSK CUISINE
    {
        id: 33,
        name: "Nikujaga (Kjøtt og poteter)",
        type: "kjøtt",
        cuisine: "japansk",
        emoji: "🥩",
        description: "Hjemmelaget japansk comfort food med tynnskåret biff og poteter",
        time: "45 min",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~38g per porsjon",
        calories: "~520 kcal per porsjon",
        ingredients: [
            "700g tynnskåret biff",
            "6 poteter",
            "3 gulrøtter",
            "2 løk",
            "1 dl soyasaus",
            "1 dl mirin",
            "1 dl sake",
            "2 ss sukker",
            "5 dl dashi (eller kyllingbuljong)",
            "2 ss olje",
            "Hakket vårløk til pynt"
        ],
        instructions: [
            "Skjær poteter og gulrøtter i biter",
            "Fres løk og kjøtt i olje til brunt",
            "Ha i poteter og gulrøtter",
            "Hell i dashi, soyasaus, mirin, sake og sukker",
            "Kok opp, senk til middels varme",
            "La småkoke i 25-30 min til poteter er møre",
            "Smak til",
            "Pynt med vårløk"
        ],
        serveTips: "Server med ris og misossuppe. For ekstra protein: Server med hardkokt egg eller tofu."
    },
    {
        id: 34,
        name: "Oyakodon (Kylling og egg)",
        type: "kylling",
        cuisine: "japansk",
        emoji: "🍳",
        description: "Klassisk japansk kylling-egg gryte servert over ris",
        time: "30 min",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~520 kcal per porsjon",
        ingredients: [
            "600g kyllingbryst eller lår",
            "8 egg",
            "3 løk",
            "2 dl dashi",
            "6 ss soyasaus",
            "4 ss mirin",
            "2 ss sake",
            "2 ss sukker",
            "4 porsjoner ris",
            "Hakket vårløk og nori til pynt"
        ],
        instructions: [
            "Kok ris",
            "Skjær kylling i biter, løk i skiver",
            "Kok opp dashi, soyasaus, mirin, sake og sukker",
            "Legg i løk, kok 2 min",
            "Ha i kylling, kok 5-7 min",
            "Visp egg lett, hell over kyllingen",
            "Dekk med lokk, la stå 1 min til egget setter seg",
            "Server over varm ris, pynt med vårløk"
        ],
        serveTips: "Server med misossuppe. For ekstra protein: Tilsett ekstra egg."
    },
    {
        id: 35,
        name: "Buri Daikon (Gullfisk og reddik)",
        type: "fisk",
        cuisine: "japansk",
        emoji: "🐟",
        description: "Vinterrett med gullfisk og daikon i soyasaus-basert saus",
        time: "1 time",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~42g per porsjon",
        calories: "~480 kcal per porsjon",
        ingredients: [
            "800g gullfisk eller laks (i skiver)",
            "1 stor daikon (eller kålrot)",
            "5 cm fersk ingefær",
            "1 dl soyasaus",
            "1 dl mirin",
            "1 dl sake",
            "2 ss sukker",
            "5 dl dashi",
            "Hakket vårløk til pynt"
        ],
        instructions: [
            "Skrell og skjær daikon i 2 cm tykke skiver",
            "Forkok daikon i vann i 15 min",
            "Skyll fisken i kokende vann raskt",
            "Kok opp dashi, soyasaus, mirin, sake og sukker",
            "Legg i daikon, kok 15 min",
            "Ha i fisk og ingefær, la småkoke 15 min",
            "Smak til",
            "Pynt med vårløk"
        ],
        serveTips: "Server med ris. For ekstra protein: Server med edamambønner."
    },
    {
        id: 36,
        name: "Yasai no Nimono (Grønnsaksgryte)",
        type: "vegetar",
        cuisine: "japansk",
        emoji: "🥕",
        description: "Japansk simringsrett med sesonggrønnsaker i dashi",
        time: "40 min",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~18g per porsjon",
        calories: "~340 kcal per porsjon",
        ingredients: [
            "400g fast tofu",
            "4 gulrøtter",
            "1 stor daikon",
            "300g shiitake-sopp",
            "200g bambuskudd",
            "6 dl dashi",
            "5 ss soyasaus",
            "3 ss mirin",
            "2 ss sake",
            "2 ss sukker",
            "Hakket vårløk og sesamfrø til pynt"
        ],
        instructions: [
            "Skjær grønnsaker og tofu i pene biter",
            "Kok opp dashi, soyasaus, mirin, sake og sukker",
            "Legg i gulrøtter og daikon, kok 15 min",
            "Ha i sopp, bambuskudd og tofu",
            "La småkoke 15 min til",
            "Smak til",
            "Pynt med vårløk og sesamfrø"
        ],
        serveTips: "Server med ris. For ekstra protein: Tilsett mer tofu eller edamambønner."
    },

    // GRESK CUISINE
    {
        id: 37,
        name: "Stifado (Oksegryte)",
        type: "kjøtt",
        cuisine: "gresk",
        emoji: "🥩",
        description: "Gresk oksegryte med perlløk, tomat og kanel",
        time: "2.5 timer",
        cookTime: "lang",
        servings: "4 porsjoner",
        protein: "~42g per porsjon",
        calories: "~600 kcal per porsjon",
        ingredients: [
            "1kg oksekjøtt",
            "500g perlløk",
            "400g hermetiske tomater",
            "1 dl rødvin",
            "5 dl oksekraft",
            "3 ss tomatpuré",
            "5 fedd hvitløk",
            "2 kanelstenger",
            "3 laurbærblad",
            "2 ss rødvinseddik",
            "1 ss honning",
            "Frisk oregano",
            "4 ss olivenolje",
            "Salt, pepper"
        ],
        instructions: [
            "Skjær kjøttet i store biter",
            "Brun kjøttet i olje, ta ut",
            "Fres perlløk til gylne",
            "Ha i hvitløk, stek 1 min",
            "Tilsett tomatpuré, stek 1 min",
            "Hell i vin, tomater og kraft",
            "Legg kjøttet tilbake med kanel og laurbær",
            "La småkoke 2 timer",
            "Rør inn eddik og honning",
            "Topp med oregano"
        ],
        serveTips: "Server med ris eller pasta. For ekstra protein: Server med fetaost."
    },
    {
        id: 38,
        name: "Kota Kapama (Gresk kyllinggryte)",
        type: "kylling",
        cuisine: "gresk",
        emoji: "🍗",
        description: "Kyllinggryte med tomat, kanel og feta",
        time: "1 time",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~540 kcal per porsjon",
        ingredients: [
            "800g kyllinglår",
            "400g hermetiske tomater",
            "3 løk",
            "5 fedd hvitløk",
            "2 dl kyllingbuljong",
            "1 dl hvitvin",
            "2 kanelstenger",
            "2 laurbærblad",
            "150g fetaost",
            "Frisk oregano og persille",
            "4 ss olivenolje",
            "Salt, pepper"
        ],
        instructions: [
            "Brun kyllinglårene i olje, ta ut",
            "Fres løk og hvitløk",
            "Tilsett tomater, vin og buljong",
            "Ha i kanel og laurbær",
            "Legg kyllingen tilbake",
            "La småkoke i 40 min",
            "Smuldr feta over",
            "Topp med oregano og persille"
        ],
        serveTips: "Server med ris eller orzo. For ekstra protein: Tilsett kikerter."
    },
    {
        id: 39,
        name: "Psarosoupa (Gresk fiskesuppe)",
        type: "fisk",
        cuisine: "gresk",
        emoji: "🐟",
        description: "Kremet fiskesuppe med sitron og dill",
        time: "45 min",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~38g per porsjon",
        calories: "~460 kcal per porsjon",
        ingredients: [
            "700g hvit fisk (torsk)",
            "4 poteter",
            "3 gulrøtter",
            "2 løk",
            "3 stilker selleri",
            "5 fedd hvitløk",
            "1 liter fiskebuljong",
            "3 dl kremfløte",
            "Saft og skall av 2 sitroner",
            "1 stor bunt fersk dill",
            "4 ss olivenolje",
            "Salt, pepper"
        ],
        instructions: [
            "Fres løk, selleri og hvitløk i olje",
            "Skjær poteter og gulrøtter, legg i",
            "Hell i buljong, kok 15 min",
            "Skjær fisk i biter, legg forsiktig i",
            "La trekke 7 min",
            "Rør inn fløte og sitronsaft",
            "Smak til med salt og pepper",
            "Topp med dill og sitronskal"
        ],
        serveTips: "Server med hvitløksbrød. For ekstra protein: Tilsett reker eller hvite bønner."
    },
    {
        id: 40,
        name: "Fasolada (Gresk bønnegryte)",
        type: "vegetar",
        cuisine: "gresk",
        emoji: "🫘",
        description: "Nasjonal gresk bønnegryte med tomat og olivenolje",
        time: "1 time",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~20g per porsjon",
        calories: "~380 kcal per porsjon",
        ingredients: [
            "800g hvite bønner (hermetiske)",
            "400g hermetiske tomater",
            "4 gulrøtter",
            "3 stilker selleri",
            "3 løk",
            "5 fedd hvitløk",
            "8 dl grønnsaksbuljong",
            "1 dl god olivenolje",
            "2 laurbærblad",
            "Frisk oregano og persille",
            "Salt, pepper"
        ],
        instructions: [
            "Fres løk, selleri og hvitløk i halvparten av oljen",
            "Skjær gulrøtter i skiver, legg i",
            "Ha i tomater og buljong",
            "Legg i bønner og laurbær",
            "La småkoke i 40 min",
            "Smak til med salt og pepper",
            "Drypp resten av oljen over",
            "Topp med oregano og persille"
        ],
        serveTips: "Server med fetaost og brød. For ekstra protein: Topp med gresk yoghurt."
    },

    // MAROKKANSK CUISINE
    {
        id: 41,
        name: "Tagine med Lam",
        type: "kjøtt",
        cuisine: "marokkansk",
        emoji: "🍖",
        description: "Marokkansk lammegryte med aprikos, mandler og ras el hanout",
        time: "2 timer",
        cookTime: "lang",
        servings: "4 porsjoner",
        protein: "~42g per porsjon",
        calories: "~600 kcal per porsjon",
        ingredients: [
            "900g lammekjøtt",
            "200g tørkede aprikoser",
            "100g mandler (ristede)",
            "3 løk",
            "4 fedd hvitløk",
            "400g hermetiske tomater",
            "4 dl lammefond",
            "3 ss ras el hanout",
            "2 ts kanel",
            "2 ts ingefær",
            "1 ts kurkuma",
            "2 ss honning",
            "Frisk koriander og mynte",
            "4 ss olivenolje",
            "Salt, pepper"
        ],
        instructions: [
            "Skjær lammet i biter, krydre med ras el hanout",
            "Brun kjøttet i olje, ta ut",
            "Fres løk og hvitløk til gyllen",
            "Ha i kanel, ingefær og kurkuma, stek 1 min",
            "Tilsett tomater og fond",
            "Legg kjøttet tilbake med aprikoser",
            "La småkoke under lokk i 1.5 timer",
            "Rør inn honning og mandler",
            "Topp med koriander og mynte"
        ],
        serveTips: "Server med couscous. For ekstra protein: Server med kikerter eller linser."
    },
    {
        id: 42,
        name: "Djaj Mqualli (Marokkansk kylling)",
        type: "kylling",
        cuisine: "marokkansk",
        emoji: "🍋",
        description: "Kyllinggryte med preserved sitron, oliven og saffran",
        time: "1.5 timer",
        cookTime: "lang",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~520 kcal per porsjon",
        ingredients: [
            "1kg kyllinglår",
            "2 preserved sitroner (eller vanlig sitron)",
            "150g grønne oliven",
            "3 løk",
            "5 fedd hvitløk",
            "5 dl kyllingbuljong",
            "0.5g saffran",
            "2 ts ingefær",
            "1 ts kurkuma",
            "Frisk koriander og persille",
            "4 ss olivenolje",
            "Salt, pepper"
        ],
        instructions: [
            "Brun kyllinglårene i olje, ta ut",
            "Fres løk og hvitløk",
            "Ha i ingefær, kurkuma og saffran",
            "Hell i buljong",
            "Legg kyllingen tilbake",
            "La småkoke i 1 time",
            "Skjær preserved sitron, legg i med oliven",
            "Kok 10 min til",
            "Topp med koriander og persille"
        ],
        serveTips: "Server med couscous eller flatbrød. For ekstra protein: Tilsett kikerter."
    },
    {
        id: 43,
        name: "Chermoula Fish Tagine",
        type: "fisk",
        cuisine: "marokkansk",
        emoji: "🐟",
        description: "Fiskegryte med chermoula-marinade, tomat og paprika",
        time: "45 min",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~38g per porsjon",
        calories: "~460 kcal per porsjon",
        ingredients: [
            "800g hvit fisk (torsk eller sei)",
            "4 paprika (ulike farger)",
            "400g hermetiske tomater",
            "3 løk",
            "6 fedd hvitløk",
            "1 stor bunt koriander",
            "1 ts paprika",
            "1 ts spisskummen",
            "1 ts koriander (frø)",
            "Saft av 2 sitroner",
            "5 dl fiskebuljong",
            "5 ss olivenolje",
            "Salt, pepper"
        ],
        instructions: [
            "Bland koriander, hvitløk, krydder, sitron og olje til chermoula",
            "Skjær fisk i biter, mariner i chermoula i 20 min",
            "Fres løk og paprika",
            "Ha i tomater og buljong",
            "La småkoke 15 min",
            "Legg fisken forsiktig i med marinade",
            "Kok 7-10 min",
            "Smak til"
        ],
        serveTips: "Server med couscous. For ekstra protein: Tilsett reker eller kikerter."
    },
    {
        id: 44,
        name: "Loubia (Marokkansk bønnegryte)",
        type: "vegetar",
        cuisine: "marokkansk",
        emoji: "🫘",
        description: "Krydret vegetargryte med hvite bønner, tomat og ras el hanout",
        time: "50 min",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~20g per porsjon",
        calories: "~390 kcal per porsjon",
        ingredients: [
            "800g hvite bønner (hermetiske)",
            "400g hermetiske tomater",
            "3 paprika",
            "4 løk",
            "6 fedd hvitløk",
            "2 ss ras el hanout",
            "1 ts paprika",
            "1 ts spisskummen",
            "8 dl grønnsaksbuljong",
            "Frisk koriander og persille",
            "4 ss olivenolje",
            "Salt, pepper"
        ],
        instructions: [
            "Fres løk, hvitløk og paprika",
            "Ha i ras el hanout, paprika og spisskummen",
            "Tilsett tomater og buljong",
            "Legg i bønner",
            "La småkoke i 30 min",
            "Smak til med salt og pepper",
            "Topp med koriander og persille"
        ],
        serveTips: "Server med couscous og harissa. For ekstra protein: Topp med hardkokt egg."
    },

    // THAI CUISINE
    {
        id: 45,
        name: "Massaman Curry",
        type: "kjøtt",
        cuisine: "thai",
        emoji: "🥜",
        description: "Mild thai-curry med storfekjøtt, poteter og peanøtter",
        time: "2 timer",
        cookTime: "lang",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~620 kcal per porsjon",
        ingredients: [
            "800g storfekjøtt",
            "400ml kokosmjølk",
            "6 poteter",
            "3 løk",
            "4 ss massaman curry paste",
            "100g peanøtter (ristede)",
            "3 dl kjøttbuljong",
            "3 ss fiskesaus",
            "2 ss tamarindpasta",
            "2 ss palmesukker",
            "3 laurbærblad",
            "2 kanelstenger",
            "Fersk basilikum",
            "2 ss olje"
        ],
        instructions: [
            "Skjær kjøttet i biter, brun godt",
            "Ta ut, fres curry paste i olje",
            "Hell i kokosmjølk, rør godt",
            "Legg kjøttet tilbake med buljong",
            "Tilsett krydder, kok under lokk i 1 time",
            "Skjær poteter, legg i med løk",
            "Kok 30 min til",
            "Rør inn fiskesaus, tamarind og sukker",
            "Topp med peanøtter og basilikum"
        ],
        serveTips: "Server med jasminris. For ekstra protein: Tilsett hardkokt egg."
    },
    {
        id: 46,
        name: "Gaeng Phed Gai (Thai rød kyllingcurry)",
        type: "kylling",
        cuisine: "thai",
        emoji: "🌶️",
        description: "Krydret thai-curry med kylling, bambus og thai-basilikum",
        time: "40 min",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~38g per porsjon",
        calories: "~540 kcal per porsjon",
        ingredients: [
            "750g kyllingbryst",
            "400ml kokosmjølk",
            "200g bambuskudd",
            "2 paprika",
            "3 ss rød curry paste",
            "3 dl kyllingbuljong",
            "3 ss fiskesaus",
            "2 ss palmesukker",
            "4 limeblade",
            "1 stor bunt thai-basilikum",
            "2 ss olje"
        ],
        instructions: [
            "Fres curry paste i olje til duftende",
            "Hell i kokosmjølk, rør godt",
            "Skjær kylling i biter, legg i",
            "Tilsett buljong og limeblade",
            "Skjær paprika, legg i med bambus",
            "La småkoke 20 min",
            "Smak til med fiskesaus og sukker",
            "Topp med thai-basilikum"
        ],
        serveTips: "Server med jasminris. For ekstra protein: Tilsett tofu eller edamambønner."
    },
    {
        id: 47,
        name: "Tom Kha Gai (Thai kokosnøtt-kyllingsuppe)",
        type: "fisk",
        cuisine: "thai",
        emoji: "🥥",
        description: "Kremet thai-suppe med fisk, galangal og sitrongress",
        time: "35 min",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~38g per porsjon",
        calories: "~480 kcal per porsjon",
        ingredients: [
            "700g hvit fisk eller laks",
            "400ml kokosmjølk",
            "300g sjampinjong",
            "3 tomater",
            "3 stilker sitrongress",
            "5 cm galangal",
            "4 limeblade",
            "3 thai-chili",
            "5 dl fiskebuljong",
            "3 ss fiskesaus",
            "3 ss limesaft",
            "2 ts sukker",
            "Fersk koriander"
        ],
        instructions: [
            "Knekk sitrongress, skjær galangal",
            "Kok buljong med aromaer og limeblade i 10 min",
            "Hell i kokosmjølk",
            "Skjær sopp og tomater, legg i",
            "Skjær fisk i biter, legg forsiktig i med chili",
            "Kok 5 min",
            "Smak til med fiskesaus, lime og sukker",
            "Topp med koriander"
        ],
        serveTips: "Server med jasminris. For ekstra protein: Tilsett reker."
    },
    {
        id: 48,
        name: "Gaeng Liang (Thai grønnsakssuppe)",
        type: "vegetar",
        cuisine: "thai",
        emoji: "🥬",
        description: "Lett thai-suppe med grønnsaker, tofu og pepperkorn",
        time: "35 min",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~18g per porsjon",
        calories: "~320 kcal per porsjon",
        ingredients: [
            "400g fast tofu",
            "300g squash",
            "200g kål",
            "200g bønner",
            "3 løk",
            "4 fedd hvitløk",
            "1 ss grønne pepperkorn",
            "8 dl grønnsaksbuljong",
            "2 ss soyasaus",
            "1 ss sesamolje",
            "Fersk basilikum og koriander"
        ],
        instructions: [
            "Bland hvitløk og pepperkorn til paste",
            "Fres pasten i olje",
            "Hell i buljong",
            "Skjær grønnsaker og tofu i biter",
            "Legg alt i suppen",
            "La småkoke 20 min",
            "Smak til med soyasaus",
            "Topp med urter"
        ],
        serveTips: "Server med ris. For ekstra protein: Tilsett mer tofu eller edamambønner."
    },

    // BRASILIANSK CUISINE
    {
        id: 49,
        name: "Feijoada",
        type: "kjøtt",
        cuisine: "brasiliansk",
        emoji: "🫘",
        description: "Brasils nasjonalrett med svarte bønner, svinekjøtt og chorizo",
        time: "2.5 timer",
        cookTime: "lang",
        servings: "4 porsjoner",
        protein: "~45g per porsjon",
        calories: "~680 kcal per porsjon",
        ingredients: [
            "500g svinekjøtt",
            "300g chorizo",
            "200g bacon",
            "800g svarte bønner (hermetiske)",
            "4 løk",
            "6 fedd hvitløk",
            "2 laurbærblad",
            "1 appelsin (saft og skall)",
            "8 dl kjøttbuljong",
            "2 ts spisskummen",
            "Fersk koriander",
            "3 ss olivenolje",
            "Salt, pepper"
        ],
        instructions: [
            "Skjær svinekjøtt, chorizo og bacon i biter",
            "Brun alt kjøtt i olje, ta ut",
            "Fres løk og hvitløk",
            "Legg kjøttet tilbake med bønner",
            "Hell i buljong, appelsin og laurbær",
            "Krydre med spisskummen",
            "La småkoke i 2 timer",
            "Smak til",
            "Topp med koriander"
        ],
        serveTips: "Server med ris, farofa og appelsinskiver. For ekstra protein: Server med stekt egg."
    },
    {
        id: 50,
        name: "Moqueca de Frango",
        type: "kylling",
        cuisine: "brasiliansk",
        emoji: "🥥",
        description: "Brasiliansk kyllinggryte med kokosmjølk, palmeølje og paprika",
        time: "1 time",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~560 kcal per porsjon",
        ingredients: [
            "800g kyllingbryst",
            "400ml kokosmjølk",
            "4 tomater",
            "3 paprika (ulike farger)",
            "4 løk",
            "6 fedd hvitløk",
            "3 ss palmeølje (eller olivenolje)",
            "Saft av 2 limer",
            "2 dl kyllingbuljong",
            "Fersk koriander",
            "Salt, pepper"
        ],
        instructions: [
            "Skjær kylling i biter, mariner med lime i 20 min",
            "Fres løk, hvitløk og paprika i olje",
            "Skjær tomater, legg i",
            "Hell i kokosmjølk og buljong",
            "Legg kyllingen i",
            "La småkoke i 30 min",
            "Smak til",
            "Topp med koriander"
        ],
        serveTips: "Server med ris og farofa. For ekstra protein: Tilsett kikerter."
    },
    {
        id: 51,
        name: "Moqueca de Peixe",
        type: "fisk",
        cuisine: "brasiliansk",
        emoji: "🐟",
        description: "Brasiliansk fiskegryte med kokosmjølk, tomat og lime",
        time: "45 min",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~38g per porsjon",
        calories: "~500 kcal per porsjon",
        ingredients: [
            "800g hvit fisk",
            "300g reker",
            "400ml kokosmjølk",
            "4 tomater",
            "3 paprika",
            "4 løk",
            "6 fedd hvitløk",
            "3 ss palmeølje",
            "Saft av 2 limer",
            "4 dl fiskebuljong",
            "Fersk koriander",
            "Salt, pepper"
        ],
        instructions: [
            "Skjær fisk i biter, mariner med lime",
            "Fres løk, hvitløk og paprika",
            "Ha i tomater og buljong",
            "Hell i kokosmjølk",
            "La småkoke 15 min",
            "Legg fisk og reker forsiktig i",
            "Kok 7 min",
            "Topp med koriander"
        ],
        serveTips: "Server med ris. For ekstra protein: Tilsett flere reker."
    },
    {
        id: 52,
        name: "Tutu de Feijão",
        type: "vegetar",
        cuisine: "brasiliansk",
        emoji: "🫘",
        description: "Kremet brasiliansk bønnepuré med løk og hvitløk",
        time: "40 min",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~20g per porsjon",
        calories: "~380 kcal per porsjon",
        ingredients: [
            "800g svarte bønner (hermetiske)",
            "4 løk",
            "6 fedd hvitløk",
            "200g maniokmel (eller mel)",
            "5 dl grønnsaksbuljong",
            "2 ss smør",
            "Fersk koriander",
            "Salt, pepper"
        ],
        instructions: [
            "Fres løk og hvitløk i smør til karamellisert",
            "Blend bønner med litt væske til kremete",
            "Hell bønnepuréen i gryten",
            "Tilsett buljong og maniokmel",
            "Rør godt, la koke 15 min",
            "Smak til",
            "Topp med koriander"
        ],
        serveTips: "Server med ris og grønnsaker. For ekstra protein: Topp med stekt egg eller cottage cheese."
    },

    // TYRKISK CUISINE
    {
        id: 53,
        name: "Kuzu Güveç (Tyrkisk lammegryte)",
        type: "kjøtt",
        cuisine: "tyrkisk",
        emoji: "🍖",
        description: "Tyrkisk lammegryte med aubergine, tomat og yoghurt",
        time: "2 timer",
        cookTime: "lang",
        servings: "4 porsjoner",
        protein: "~42g per porsjon",
        calories: "~580 kcal per porsjon",
        ingredients: [
            "900g lammekjøtt",
            "2 auberginer",
            "4 tomater",
            "3 paprika",
            "4 løk",
            "6 fedd hvitløk",
            "2 dl gresk yoghurt",
            "5 dl lammefond",
            "2 ts paprika",
            "1 ts spisskummen",
            "Frisk mynte og persille",
            "4 ss olivenolje",
            "Salt, pepper"
        ],
        instructions: [
            "Skjær lammet i biter, brun i olje",
            "Ta ut, skjær aubergine og paprika",
            "Fres grønnsaker",
            "Legg lammet tilbake",
            "Ha i tomater og fond",
            "Krydre med paprika og spisskummen",
            "La småkoke i 1.5 timer",
            "Rør inn yoghurt",
            "Topp med mynte og persille"
        ],
        serveTips: "Server med bulgur eller ris. For ekstra protein: Server med ekstra yoghurt."
    },
    {
        id: 54,
        name: "Tavuk Güveç (Tyrkisk kyllinggryte)",
        type: "kylling",
        cuisine: "tyrkisk",
        emoji: "🍗",
        description: "Tyrkisk kylling med grønnsaker, tomat og kashkaval-ost",
        time: "1 time",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~540 kcal per porsjon",
        ingredients: [
            "800g kyllingbryst",
            "3 paprika",
            "2 auberginer",
            "400g hermetiske tomater",
            "4 løk",
            "6 fedd hvitløk",
            "150g kashkaval (eller mozzarella)",
            "4 dl kyllingbuljong",
            "2 ts paprika",
            "Frisk persille",
            "4 ss olivenolje",
            "Salt, pepper"
        ],
        instructions: [
            "Skjær kylling i biter, brun i olje",
            "Ta ut, fres løk og hvitløk",
            "Skjær paprika og aubergine, legg i",
            "Ha i tomater og buljong",
            "Krydre med paprika",
            "Legg kyllingen tilbake",
            "La småkoke 30 min",
            "Topp med ost, gratiner 5 min",
            "Pynt med persille"
        ],
        serveTips: "Server med bulgur eller brød. For ekstra protein: Tilsett kikerter."
    },
    {
        id: 55,
        name: "Balık Güveç (Tyrkisk fiskegryte)",
        type: "fisk",
        cuisine: "tyrkisk",
        emoji: "🐟",
        description: "Tyrkisk fiskegryte med tomat, paprika og dill",
        time: "40 min",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~38g per porsjon",
        calories: "~460 kcal per porsjon",
        ingredients: [
            "800g hvit fisk",
            "4 tomater",
            "3 paprika",
            "3 løk",
            "6 fedd hvitløk",
            "5 dl fiskebuljong",
            "2 dl hvitvin",
            "1 stor bunt fersk dill",
            "Saft av 1 sitron",
            "4 ss olivenolje",
            "Salt, pepper"
        ],
        instructions: [
            "Fres løk, hvitløk og paprika",
            "Skjær tomater, legg i",
            "Hell i vin og buljong",
            "La småkoke 15 min",
            "Skjær fisk i biter",
            "Legg forsiktig i",
            "Kok 7 min",
            "Rør inn dill og sitronsaft"
        ],
        serveTips: "Server med bulgur. For ekstra protein: Tilsett reker."
    },
    {
        id: 56,
        name: "İmam Bayıldı",
        type: "vegetar",
        cuisine: "tyrkisk",
        emoji: "🍆",
        description: "Fylt aubergine med tomat, løk og hvitløk",
        time: "1 time",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~18g per porsjon",
        calories: "~360 kcal per porsjon",
        ingredients: [
            "4 store auberginer",
            "400g hermetiske tomater",
            "400g kikerter (hermetiske)",
            "5 løk",
            "8 fedd hvitløk",
            "1 dl olivenolje",
            "2 ss tomatpuré",
            "1 ss sukker",
            "Frisk persille",
            "Salt, pepper"
        ],
        instructions: [
            "Skjær auberginer på langs, salt og la stå 20 min",
            "Fres løk og hvitløk i olje",
            "Ha i tomater, tomatpuré og sukker",
            "Tilsett kikerter, kok 10 min",
            "Skyll auberginer, legg i ovnsform",
            "Fyll med tomatblanding",
            "Drypp olje over, dekk med folie",
            "Stek på 180°C i 40 min",
            "Topp med persille"
        ],
        serveTips: "Server med bulgur og yoghurt. For ekstra protein: Server med gresk yoghurt."
    }

];
