// Recipe database - Praktiske gryter med vanlige ingredienser
const recipes = [
    // ===== KJAPPE HVERDAGSGRYTER (under 45 min) =====

    // NORDISK - RASK
    {
        id: 1,
        name: "Pølsegryte",
        type: "kjøtt",
        cuisine: "nordisk",
        emoji: "🌭",
        description: "Enkel hverdagsgryte med pølser, grønnsaker og tomatsaus",
        time: "30 minutter",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~20g per porsjon",
        calories: "~420 kcal per porsjon",
        ingredients: [
            "8 grillpølser, skåret i biter",
            "2 løk, hakket",
            "2 paprika, i terninger",
            "1 squash, i terninger",
            "1 boks hakkede tomater (400g)",
            "2 ss tomatpuré",
            "3 dl vann eller buljong",
            "2 ts paprikapulver",
            "1 ts oregano",
            "Salt, pepper",
            "Olje til steking"
        ],
        instructions: [
            "Fres løk i olje i en stor gryte i 3 min",
            "Tilsett pølsebiter, stek i 5 min",
            "Ha i paprika og squash, stek i 3 min",
            "Tilsett hakkede tomater, tomatpuré, vann og krydder",
            "La småkoke i 15 min",
            "Smak til med salt og pepper"
        ],
        serveTips: "Server med ris, pasta eller brød. Perfekt for unger!"
    },
    {
        id: 2,
        name: "Fiskesuppe",
        type: "fisk",
        cuisine: "nordisk",
        emoji: "🐟",
        description: "Kremet fiskesuppe med torsk og grønnsaker",
        time: "35 minutter",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~32g per porsjon",
        calories: "~380 kcal per porsjon",
        ingredients: [
            "600g torsk eller sei, i biter",
            "3 gulrøtter, i terninger",
            "2 poteter, i terninger",
            "1 løk, hakket",
            "1 liter fiskebuljong",
            "2 dl fløte",
            "2 ss smør",
            "Frisk dill",
            "Salt, pepper"
        ],
        instructions: [
            "Fres løk i smør i 3 min",
            "Tilsett gulrøtter og poteter, fres i 2 min",
            "Hell på fiskebuljong, kok i 15 min til grønnsakene er myke",
            "Legg i fiskebiter, la småkoke i 5-7 min",
            "Rør inn fløte, varm gjennom",
            "Topp med frisk dill"
        ],
        serveTips: "Server med godt brød. Kan fryses uten fløte."
    },
    {
        id: 3,
        name: "Kylling i Karrisaus",
        type: "kylling",
        cuisine: "asiatisk",
        emoji: "🍛",
        description: "Kremet kyllinggryte med curry og grønnsaker",
        time: "30 minutter",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~38g per porsjon",
        calories: "~480 kcal per porsjon",
        ingredients: [
            "600g kyllingfilet, i terninger",
            "1 løk, hakket",
            "2 paprika, i strimler",
            "1 boks kokosnøttmelk (400ml)",
            "2 ss karripasta (gul eller rød)",
            "1 ss soyasaus",
            "1 ts honning",
            "Olje til steking",
            "Salt, pepper"
        ],
        instructions: [
            "Stek kyllingbiter i olje til gyldne, ta opp",
            "Fres løk i samme gryte i 3 min",
            "Tilsett karripasta, fres i 1 min",
            "Hell på kokosnøttmelk, soyasaus og honning",
            "Legg kyllingen tilbake, tilsett paprika",
            "La småkoke i 10 min",
            "Smak til med salt og pepper"
        ],
        serveTips: "Server med ris eller naanbrød. Juster styrken med mengde karripasta."
    },
    {
        id: 4,
        name: "Vegetar Chili",
        type: "vegetar",
        cuisine: "meksikansk",
        emoji: "🌶️",
        description: "Mettende chili med bønner, mais og paprika",
        time: "35 minutter",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~18g per porsjon",
        calories: "~340 kcal per porsjon",
        ingredients: [
            "2 boks kidney-bønner (à 400g)",
            "1 boks svarte bønner (400g)",
            "1 boks hakkede tomater (400g)",
            "1 boks mais (200g)",
            "2 løk, hakket",
            "2 paprika, i terninger",
            "3 fedd hvitløk, presset",
            "2 ss chilipulver",
            "1 ss spisskummen",
            "1 ts paprikapulver",
            "2 ss tomatpuré",
            "Salt, pepper",
            "Olje til steking"
        ],
        instructions: [
            "Fres løk og hvitløk i olje i 5 min",
            "Tilsett paprika, fres i 3 min",
            "Ha i tomatpuré og krydder, fres i 1 min",
            "Tilsett hakkede tomater, bønner og mais",
            "La småkoke i 20 min",
            "Smak til med salt og pepper"
        ],
        serveTips: "Server med ris, rømme og nacho-chips. For ekstra protein: Topp med revet ost."
    },
    {
        id: 5,
        name: "Kjøttdeig Taco-gryte",
        type: "kjøtt",
        cuisine: "meksikansk",
        emoji: "🌮",
        description: "Rask og enkel taco-gryte med kjøttdeig",
        time: "25 minutter",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~35g per porsjon",
        calories: "~520 kcal per porsjon",
        ingredients: [
            "600g kjøttdeig",
            "1 pose tacokrydder",
            "1 løk, hakket",
            "2 paprika, i terninger",
            "1 boks kidney-bønner (400g)",
            "1 boks hakkede tomater (400g)",
            "2 dl vann",
            "Olje til steking"
        ],
        instructions: [
            "Brun kjøttdeig i gryte, hell av fett",
            "Tilsett løk, fres i 3 min",
            "Ha i paprika, fres i 2 min",
            "Tilsett tacokrydder, hakkede tomater, bønner og vann",
            "La småkoke i 15 min",
            "Klar til servering!"
        ],
        serveTips: "Server med ris, rømme, salsa og nachos. Perfekt fredagsmiddag!"
    },
    {
        id: 6,
        name: "Pasta Carbonara-gryte",
        type: "kjøtt",
        cuisine: "italiensk",
        emoji: "🍝",
        description: "Kremet pasta med bacon i én gryte",
        time: "25 minutter",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~28g per porsjon",
        calories: "~620 kcal per porsjon",
        ingredients: [
            "400g pasta (penne eller fusilli)",
            "200g bacon, i terninger",
            "1 løk, hakket",
            "3 fedd hvitløk, presset",
            "6 dl kyllingbuljong",
            "3 dl fløte",
            "100g parmesan, revet",
            "Persille",
            "Salt, pepper"
        ],
        instructions: [
            "Stek bacon sprøtt i gryte, ta opp",
            "Fres løk og hvitløk i baconfettet i 2 min",
            "Ha i pasta og buljong, kok på høy varme",
            "Rør ofte, la pastaen koke i 10-12 min til myk",
            "Rør inn fløte og parmesan",
            "Legg bacon tilbake, topp med persille"
        ],
        serveTips: "Alt lages i én gryte - perfekt for travle hverdager!"
    },
    {
        id: 7,
        name: "Kylling Tikka Masala",
        type: "kylling",
        cuisine: "indisk",
        emoji: "🍗",
        description: "Kremet indisk kyllinggryte med yoghurt og krydder",
        time: "40 minutter",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~42g per porsjon",
        calories: "~520 kcal per porsjon",
        ingredients: [
            "700g kyllingfilet, i terninger",
            "1 løk, hakket",
            "3 fedd hvitløk, presset",
            "1 ss ingefær, revet",
            "2 ss garam masala",
            "1 ts chili",
            "1 ts paprikapulver",
            "1 boks hakkede tomater (400g)",
            "2 dl fløte",
            "2 dl naturell yoghurt",
            "2 ss tomatpuré",
            "Smør til steking",
            "Frisk koriander"
        ],
        instructions: [
            "Bland kylling med 1 ss garam masala og yoghurt, la stå 10 min",
            "Stek kyllingen i smør til gyllen, ta opp",
            "Fres løk, hvitløk og ingefær i 3 min",
            "Tilsett resten av kryddene og tomatpuré, fres i 1 min",
            "Ha i hakkede tomater, kok i 10 min",
            "Rør inn fløte, legg kyllingen tilbake",
            "La småkoke i 10 min, topp med koriander"
        ],
        serveTips: "Server med ris og naanbrød. Juster chili etter smak."
    },
    {
        id: 8,
        name: "Laks i Kremet Dillsaus",
        type: "fisk",
        cuisine: "nordisk",
        emoji: "🐟",
        description: "Enkel laksegryte med fløte og dill",
        time: "30 minutter",
        cookTime: "rask",
        servings: "4 porsjoner",
        protein: "~36g per porsjon",
        calories: "~420 kcal per porsjon",
        ingredients: [
            "600g laksefilet, i biter",
            "1 løk, hakket",
            "2 dl hvitvin (eller buljong)",
            "3 dl fløte",
            "1 dl crème fraiche",
            "Juice fra 1/2 sitron",
            "Frisk dill",
            "2 ss smør",
            "Salt, pepper"
        ],
        instructions: [
            "Fres løk i smør i 3 min",
            "Hell på hvitvin, kok inn til halv mengde",
            "Tilsett fløte, la småkoke i 5 min",
            "Legg i laksebiter, la småkoke i 8 min",
            "Rør inn crème fraiche og sitronjuice",
            "Topp med frisk dill"
        ],
        serveTips: "Server med poteter eller ris. Bruker du buljong i stedet for vin, fungerer det også fint!"
    },

    // ===== MIDDELS GRYTER (45 min - 1,5 timer) =====

    {
        id: 9,
        name: "Kjøttboller i Saus",
        type: "kjøtt",
        cuisine: "nordisk",
        emoji: "🍖",
        description: "Klassiske kjøttboller i brun saus",
        time: "1 time",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~38g per porsjon",
        calories: "~580 kcal per porsjon",
        ingredients: [
            "600g kjøttdeig",
            "1 egg",
            "1 dl brødkrummer",
            "1 dl melk",
            "1 løk, finhakket",
            "Salt, pepper",
            "Smør til steking",
            "--- Saus ---",
            "3 ss smør",
            "3 ss mel",
            "6 dl oksekraft",
            "2 ss soyasaus",
            "1 ss rømme"
        ],
        instructions: [
            "Bland kjøttdeig, egg, brødkrummer, melk, løk, salt og pepper",
            "Form til kjøttboller, stek i smør til brune, ta opp",
            "Smelt smør i samme gryte, rør inn mel",
            "Hell på kraft litt om gangen, pisk godt",
            "Tilsett soyasaus, legg kjøttbollene tilbake",
            "La småkoke i 20 min",
            "Rør inn rømme før servering"
        ],
        serveTips: "Server med poteter, tyttebær og agurksalat."
    },
    {
        id: 10,
        name: "Lapskaus",
        type: "kjøtt",
        cuisine: "nordisk",
        emoji: "🥩",
        description: "Norsk tradisjonskjøtt med rotgrønnsaker",
        time: "1,5 timer",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~35g per porsjon",
        calories: "~480 kcal per porsjon",
        ingredients: [
            "600g oksekjøtt, i terninger",
            "4 poteter, i terninger",
            "3 gulrøtter, i terninger",
            "1 kålrot, i terninger",
            "2 løk, hakket",
            "8 dl kjøttbuljong",
            "2 laurbærblad",
            "Salt, pepper, spisskummen",
            "Olje til steking"
        ],
        instructions: [
            "Brun kjøttet i porsjoner, ta opp",
            "Fres løk i samme gryte i 5 min",
            "Legg kjøttet tilbake, hell på buljong",
            "Tilsett laurbærblad og spisskummen",
            "La småkoke i 45 min",
            "Tilsett rotgrønnsaker, kok i 30 min til",
            "Smak til med salt og pepper"
        ],
        serveTips: "Server med flatbrød. Smaker bedre dagen etter!"
    },
    {
        id: 11,
        name: "Kylling Cacciatore",
        type: "kylling",
        cuisine: "italiensk",
        emoji: "🍗",
        description: "Italiensk kyllinggryte med tomat, paprika og oliven",
        time: "1 time",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~40g per porsjon",
        calories: "~460 kcal per porsjon",
        ingredients: [
            "8 kyllinglår",
            "2 løk, hakket",
            "3 fedd hvitløk, presset",
            "2 paprika, i strimler",
            "1 boks hakkede tomater (400g)",
            "2 dl hvitvin (eller buljong)",
            "100g svarte oliven",
            "2 ts oregano",
            "1 ts basilikum",
            "Oliveolje",
            "Salt, pepper"
        ],
        instructions: [
            "Brun kyllinglårene i olje, ta opp",
            "Fres løk og hvitløk i 5 min",
            "Tilsett paprika, fres i 3 min",
            "Hell på hvitvin, kok inn litt",
            "Ha i hakkede tomater, krydder og oliven",
            "Legg kyllingen tilbake",
            "La småkoke i 40 min"
        ],
        serveTips: "Server med pasta eller godt brød."
    },
    {
        id: 12,
        name: "Ertesuppe",
        type: "vegetar",
        cuisine: "nordisk",
        emoji: "🍲",
        description: "Klassisk norsk ertesuppe, mettende og enkel",
        time: "1,5 timer",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~20g per porsjon",
        calories: "~380 kcal per porsjon",
        ingredients: [
            "400g gule erter, tørket",
            "2 gulrøtter, i terninger",
            "1 liten kålrot, i terninger",
            "1 løk, hakket",
            "1,5 liter grønnsaksbuljong",
            "2 ts timian",
            "Salt, pepper",
            "Smør til servering"
        ],
        instructions: [
            "Skyll ertene, legg i gryte",
            "Tilsett buljong, kok opp",
            "Skum av, senk varmen",
            "Tilsett løk, gulrøtter og kålrot",
            "La småkoke i 1-1,5 timer til ertene er myke",
            "Tilsett timian, smak til med salt og pepper",
            "Server med en klatt smør"
        ],
        serveTips: "Server med knekkebrød. For ekstra protein: Tilsett kokte egg eller serv med pølse."
    },

    // ===== HELGEGRYTER (over 1,5 timer) =====

    {
        id: 13,
        name: "Oksegryte",
        type: "kjøtt",
        cuisine: "nordisk",
        emoji: "🥩",
        description: "Mørt oksekjøtt i rik brun saus",
        time: "2,5 timer",
        cookTime: "lang",
        servings: "4 porsjoner",
        protein: "~45g per porsjon",
        calories: "~620 kcal per porsjon",
        ingredients: [
            "800g oksegryte, i terninger",
            "2 løk, hakket",
            "3 gulrøtter, i biter",
            "200g bacon, i terninger",
            "3 ss tomatpuré",
            "4 dl rødvin",
            "6 dl oksekraft",
            "2 laurbærblad",
            "2 ts timian",
            "Mel til panering",
            "Salt, pepper",
            "Olje til steking"
        ],
        instructions: [
            "Vend kjøttet i mel, salt og pepper",
            "Brun kjøttet i porsjoner, ta opp",
            "Stek bacon sprøtt, ta opp",
            "Fres løk i fettet i 5 min",
            "Ha i tomatpuré, fres i 2 min",
            "Hell på rødvin, kok inn til halv mengde",
            "Tilsett kraft, kjøtt, bacon, gulrøtter, laurbær og timian",
            "La småkoke på lav varme i 2 timer til kjøttet er mørt"
        ],
        serveTips: "Server med potetmos eller kokte poteter. Perfekt søndagsmiddag!"
    },
    {
        id: 14,
        name: "Coq au Vin",
        type: "kylling",
        cuisine: "italiensk",
        emoji: "🍗",
        description: "Fransk klassiker med kylling i rødvinssaus",
        time: "2 timer",
        cookTime: "lang",
        servings: "4 porsjoner",
        protein: "~42g per porsjon",
        calories: "~580 kcal per porsjon",
        ingredients: [
            "8 kyllinglår",
            "150g bacon, i terninger",
            "200g små champinjoner",
            "12 sjalottløk",
            "3 fedd hvitløk, presset",
            "5 dl rødvin",
            "3 dl kyllingbuljong",
            "2 ss tomatpuré",
            "2 laurbærblad",
            "2 ts timian",
            "2 ss smør",
            "2 ss mel",
            "Salt, pepper"
        ],
        instructions: [
            "Brun kyllinglårene i smør, ta opp",
            "Stek bacon sprøtt, ta opp",
            "Fres sjalottløk og sopp i 5 min, ta opp",
            "Fres hvitløk i 1 min",
            "Dryss mel over, rør godt",
            "Hell på rødvin og buljong, tilsett tomatpuré, laurbær og timian",
            "Legg kylling, bacon, løk og sopp tilbake",
            "La småkoke i 1,5 timer"
        ],
        serveTips: "Server med potetmos. Smaker fantastisk dagen etter!"
    },
    {
        id: 15,
        name: "Pulled Pork",
        type: "kjøtt",
        cuisine: "meksikansk",
        emoji: "🥩",
        description: "Langkokt svinekam som faller fra hverandre",
        time: "3 timer",
        cookTime: "lang",
        servings: "6 porsjoner",
        protein: "~48g per porsjon",
        calories: "~520 kcal per porsjon",
        ingredients: [
            "1,5 kg svinestek (nakke eller bog)",
            "2 løk, grovhakket",
            "4 fedd hvitløk, presset",
            "2 ss paprikapulver",
            "1 ss chilipulver",
            "1 ss spisskummen",
            "2 ss brun sukker",
            "3 dl BBQ-saus",
            "2 dl eplecidereddik",
            "2 dl vann",
            "Salt, pepper",
            "Olje til steking"
        ],
        instructions: [
            "Gni kjøttet med paprikapulver, chili, spisskummen, sukker, salt og pepper",
            "Brun kjøttet på alle sider i stor gryte",
            "Tilsett løk, hvitløk, BBQ-saus, eddik og vann",
            "Kok opp, dekk til",
            "Stek i ovn på 150°C i 2,5-3 timer",
            "Ta ut kjøttet, trekk fra hverandre med to gafler",
            "Kok sausen inn litt, bland kjøttet tilbake"
        ],
        serveTips: "Server i burgerbrød med coleslaw. Perfekt til fest!"
    },
    {
        id: 16,
        name: "Vegetar Linsebolognese",
        type: "vegetar",
        cuisine: "italiensk",
        emoji: "🍝",
        description: "Mettende kjøttfri bolognese med linser",
        time: "1 time",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~18g per porsjon",
        calories: "~360 kcal per porsjon",
        ingredients: [
            "300g røde eller grønne linser",
            "2 løk, hakket",
            "3 gulrøtter, revet",
            "3 stilker selleri, hakket",
            "3 fedd hvitløk, presset",
            "2 boks hakkede tomater (à 400g)",
            "2 ss tomatpuré",
            "2 dl rødvin (eller buljong)",
            "2 ts oregano",
            "1 ts basilikum",
            "Oliveolje",
            "Salt, pepper"
        ],
        instructions: [
            "Fres løk, gulrøtter og selleri i olje i 10 min",
            "Tilsett hvitløk og tomatpuré, fres i 2 min",
            "Ha i linser, hakkede tomater, rødvin og krydder",
            "La småkoke i 40 min til linsene er myke",
            "Smak til med salt og pepper"
        ],
        serveTips: "Server med pasta og parmesan. For ekstra protein: Topp med mozarella."
    },
    {
        id: 17,
        name: "Butter Chicken",
        type: "kylling",
        cuisine: "indisk",
        emoji: "🍗",
        description: "Kremet indisk kyllingrett med smørrik tomatsaus",
        time: "1,5 timer",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~44g per porsjon",
        calories: "~620 kcal per porsjon",
        ingredients: [
            "700g kyllingfilet, i terninger",
            "200g yoghurt naturell",
            "2 ss tandoori-krydder",
            "--- Saus ---",
            "1 løk, hakket",
            "3 fedd hvitløk, presset",
            "2 ss ingefær, revet",
            "1 boks hakkede tomater (400g)",
            "2 dl fløte",
            "100g smør",
            "2 ss garam masala",
            "1 ts chili",
            "2 ts paprikapulver",
            "1 ss honning",
            "Salt"
        ],
        instructions: [
            "Bland kylling med yoghurt og tandoori-krydder, mariner 30 min",
            "Stek kyllingen i smør til gyllen, ta opp",
            "Fres løk, hvitløk og ingefær i samme gryte i 5 min",
            "Tilsett garam masala, chili og paprikapulver, fres i 1 min",
            "Ha i hakkede tomater, kok i 15 min",
            "Blend sausen glatt, hell tilbake i gryte",
            "Rør inn fløte, smør og honning",
            "Legg kyllingen tilbake, varm i 10 min"
        ],
        serveTips: "Server med ris og naanbrød. En av de mest populære indiske rettene!"
    },
    {
        id: 18,
        name: "Chili con Carne",
        type: "kjøtt",
        cuisine: "meksikansk",
        emoji: "🌶️",
        description: "Klassisk tex-mex gryte med kjøttdeig og bønner",
        time: "1,5 timer",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~38g per porsjon",
        calories: "~580 kcal per porsjon",
        ingredients: [
            "600g kjøttdeig",
            "2 løk, hakket",
            "3 fedd hvitløk, presset",
            "2 paprika, i terninger",
            "1 boks kidney-bønner (400g)",
            "2 boks hakkede tomater (à 400g)",
            "2 ss tomatpuré",
            "2 ss chilipulver",
            "1 ss spisskummen",
            "1 ts paprikapulver",
            "1 ts oregano",
            "2 dl oksekraft",
            "1 mørk sjokolade (20g)",
            "Salt, pepper",
            "Olje til steking"
        ],
        instructions: [
            "Brun kjøttdeig i gryte, hell av fett",
            "Tilsett løk og hvitløk, fres i 5 min",
            "Ha i paprika, fres i 3 min",
            "Tilsett tomatpuré og krydder, fres i 2 min",
            "Ha i hakkede tomater, bønner og kraft",
            "La småkoke i 1 time",
            "Rør inn sjokolade, la smelte",
            "Smak til med salt og pepper"
        ],
        serveTips: "Server med ris, rømme, revet ost og nachos. Sjokoladen gir dybde i smaken!"
    },
    {
        id: 19,
        name: "Fiskesuppe Deluxe",
        type: "fisk",
        cuisine: "nordisk",
        emoji: "🦐",
        description: "Luksuriøs fiskesuppe med blandet sjømat",
        time: "1 time",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~36g per porsjon",
        calories: "~420 kcal per porsjon",
        ingredients: [
            "400g hvit fisk (torsk/sei), i biter",
            "200g reker, skalte",
            "200g blåskjell",
            "2 gulrøtter, i terninger",
            "2 poteter, i terninger",
            "1 purre, i skiver",
            "1 løk, hakket",
            "2 fedd hvitløk, presset",
            "1 liter fiskebuljong",
            "2 dl hvitvin",
            "2 dl fløte",
            "3 ss smør",
            "Frisk dill og persille",
            "Salt, pepper"
        ],
        instructions: [
            "Fres løk, hvitløk og purre i smør i 5 min",
            "Tilsett gulrøtter og poteter, fres i 3 min",
            "Hell på hvitvin, kok inn litt",
            "Tilsett fiskebuljong, kok i 15 min",
            "Legg i fisk og blåskjell, la småkoke i 5 min",
            "Tilsett reker og fløte, varm gjennom",
            "Topp med frisk dill og persille"
        ],
        serveTips: "Server med godt brød. En luksuriøs helgemiddag!"
    },
    {
        id: 20,
        name: "Grønnsaksgryte med Kikerter",
        type: "vegetar",
        cuisine: "asiatisk",
        emoji: "🥘",
        description: "Krydret vegetargryte inspirert av indisk kjøkken",
        time: "1 time",
        cookTime: "middels",
        servings: "4 porsjoner",
        protein: "~16g per porsjon",
        calories: "~380 kcal per porsjon",
        ingredients: [
            "2 boks kikerter (à 400g)",
            "1 blomkål, i buketter",
            "2 søtpoteter, i terninger",
            "1 aubergine, i terninger",
            "1 løk, hakket",
            "3 fedd hvitløk, presset",
            "1 ss ingefær, revet",
            "1 boks kokosnøttmelk (400ml)",
            "1 boks hakkede tomater (400g)",
            "2 ss karripasta",
            "2 ts garam masala",
            "Spinat",
            "Olje til steking",
            "Salt"
        ],
        instructions: [
            "Fres løk, hvitløk og ingefær i olje i 5 min",
            "Tilsett karripasta og garam masala, fres i 2 min",
            "Ha i aubergine og søtpoteter, fres i 5 min",
            "Tilsett hakkede tomater og kokosnøttmelk",
            "La småkoke i 20 min",
            "Tilsett blomkål og kikerter, kok i 15 min",
            "Rør inn spinat til den faller sammen"
        ],
        serveTips: "Server med ris eller naanbrød. For ekstra protein: Topp med yoghurt og cashewnøtter."
    }
];
